// ============================================================
// VOCABULARY DATABASE - Complete A1 Vocabulary
// Berliner Platz 1 Neu - All 12 Chapters
// ============================================================

const VOCABULARY = [
  // ── CHAPTER 1: Hallo ──────────────────────────────────────
  { id:1,  ch:1, de:"Hallo",           ar:"مرحباً",              type:"phrase",  example:"Hallo! Ich bin Maria." },
  { id:2,  ch:1, de:"Guten Tag",       ar:"مرحباً / صباح الخير",  type:"phrase",  example:"Guten Tag! Wie heißen Sie?" },
  { id:3,  ch:1, de:"Guten Morgen",    ar:"صباح الخير",           type:"phrase",  example:"Guten Morgen, Frau Kohl!" },
  { id:4,  ch:1, de:"Guten Abend",     ar:"مساء الخير",           type:"phrase",  example:"Guten Abend!" },
  { id:5,  ch:1, de:"Auf Wiedersehen", ar:"مع السلامة (رسمي)",     type:"phrase",  example:"Auf Wiedersehen! Tschüss!" },
  { id:6,  ch:1, de:"Tschüss",         ar:"مع السلامة (غير رسمي)", type:"phrase",  example:"Tschüss! Bis morgen!" },
  { id:7,  ch:1, de:"Bitte",           ar:"من فضلك / عفواً",       type:"phrase",  example:"Buchstabieren Sie bitte." },
  { id:8,  ch:1, de:"Danke",           ar:"شكراً",                type:"phrase",  example:"Danke schön!" },
  { id:9,  ch:1, de:"der Name",        ar:"الاسم",                type:"noun",    example:"Wie ist Ihr Name?" },
  { id:10, ch:1, de:"heißen",          ar:"يُسمّى / اسمه",         type:"verb",    example:"Ich heiße Maria." },
  { id:11, ch:1, de:"sein",            ar:"يكون / يوجد",           type:"verb",    example:"Ich bin Carlos." },
  { id:12, ch:1, de:"kommen",          ar:"يأتي",                 type:"verb",    example:"Woher kommen Sie?" },
  { id:13, ch:1, de:"wohnen",          ar:"يسكن / يقطن",           type:"verb",    example:"Ich wohne in Berlin." },
  { id:14, ch:1, de:"sprechen",        ar:"يتحدث / يتكلم",         type:"verb",    example:"Ich spreche Arabisch und Deutsch." },
  { id:15, ch:1, de:"aus Deutschland", ar:"من ألمانيا",            type:"phrase",  example:"Ich komme aus Deutschland." },
  { id:16, ch:1, de:"die Sprache",     ar:"اللغة",                type:"noun",    example:"Welche Sprache sprechen Sie?" },
  { id:17, ch:1, de:"das Land",        ar:"البلد / الدولة",         type:"noun",    example:"Aus welchem Land kommen Sie?" },
  { id:18, ch:1, de:"der Kurs",        ar:"الدورة / الكورس",        type:"noun",    example:"Der Deutschkurs beginnt um 9 Uhr." },
  { id:19, ch:1, de:"buchstabieren",   ar:"يتهجأ",                type:"verb",    example:"Buchstabieren Sie bitte Ihren Namen." },
  { id:20, ch:1, de:"das Alphabet",    ar:"الأبجدية",              type:"noun",    example:"Das deutsche Alphabet hat 26 Buchstaben." },
  { id:21, ch:1, de:"ich",             ar:"أنا",                  type:"pronoun", example:"Ich heiße Carlos." },
  { id:22, ch:1, de:"du",              ar:"أنتَ (غير رسمي)",        type:"pronoun", example:"Wie heißt du?" },
  { id:23, ch:1, de:"Sie",             ar:"حضرتك (رسمي)",          type:"pronoun", example:"Wie heißen Sie?" },
  { id:24, ch:1, de:"er / sie / es",   ar:"هو / هي / إنه",         type:"pronoun", example:"Er heißt Thomas." },
  { id:25, ch:1, de:"wir",             ar:"نحن",                  type:"pronoun", example:"Wir kommen aus Spanien." },

  // ── CHAPTER 2: Wie geht's ─────────────────────────────────
  { id:26, ch:2, de:"Wie geht's?",     ar:"كيف حالك؟",            type:"phrase",  example:"Hallo! Wie geht's?" },
  { id:27, ch:2, de:"gut",             ar:"جيد / بخير",            type:"adj",     example:"Danke, gut!" },
  { id:28, ch:2, de:"nicht gut",       ar:"ليس جيداً",             type:"phrase",  example:"Mir geht es nicht gut." },
  { id:29, ch:2, de:"es geht",         ar:"لا بأس / يمشي",          type:"phrase",  example:"Es geht. Ich bin müde." },
  { id:30, ch:2, de:"müde",            ar:"متعب",                 type:"adj",     example:"Ich bin sehr müde." },
  { id:31, ch:2, de:"krank",           ar:"مريض",                 type:"adj",     example:"Ich bin krank." },
  { id:32, ch:2, de:"der Kaffee",      ar:"القهوة",                type:"noun",    example:"Ich trinke einen Kaffee." },
  { id:33, ch:2, de:"der Tee",         ar:"الشاي",                 type:"noun",    example:"Möchten Sie Tee?" },
  { id:34, ch:2, de:"das Wasser",      ar:"الماء",                 type:"noun",    example:"Ein Wasser, bitte." },
  { id:35, ch:2, de:"die Milch",       ar:"الحليب",                type:"noun",    example:"Kaffee mit Milch, bitte." },
  { id:36, ch:2, de:"trinken",         ar:"يشرب",                 type:"verb",    example:"Was möchten Sie trinken?" },
  { id:37, ch:2, de:"möchten",         ar:"يريد / يودّ",            type:"verb",    example:"Ich möchte einen Kaffee." },
  { id:38, ch:2, de:"null",            ar:"صفر (0)",               type:"number",  example:"Die Zahl null." },
  { id:39, ch:2, de:"eins",            ar:"واحد (1)",              type:"number",  example:"Eins, zwei, drei..." },
  { id:40, ch:2, de:"zwei",            ar:"اثنان (2)",             type:"number",  example:"Ich habe zwei Kinder." },
  { id:41, ch:2, de:"drei",            ar:"ثلاثة (3)",             type:"number",  example:"Drei Euro, bitte." },
  { id:42, ch:2, de:"vier",            ar:"أربعة (4)",             type:"number",  example:"Vier Personen." },
  { id:43, ch:2, de:"fünf",            ar:"خمسة (5)",              type:"number",  example:"Fünf Euro." },
  { id:44, ch:2, de:"sechs",           ar:"ستة (6)",               type:"number",  example:"Sechs Uhr." },
  { id:45, ch:2, de:"sieben",          ar:"سبعة (7)",              type:"number",  example:"Sieben Tage." },
  { id:46, ch:2, de:"acht",            ar:"ثمانية (8)",             type:"number",  example:"Acht Stunden." },
  { id:47, ch:2, de:"neun",            ar:"تسعة (9)",              type:"number",  example:"Neun Uhr." },
  { id:48, ch:2, de:"zehn",            ar:"عشرة (10)",             type:"number",  example:"Zehn Euro." },
  { id:49, ch:2, de:"zwanzig",         ar:"عشرون (20)",            type:"number",  example:"Zwanzig Minuten." },
  { id:50, ch:2, de:"hundert",         ar:"مئة (100)",             type:"number",  example:"Hundert Euro." },
  { id:51, ch:2, de:"die Telefonnummer",ar:"رقم الهاتف",           type:"noun",    example:"Was ist Ihre Telefonnummer?" },
  { id:52, ch:2, de:"die Cafeteria",   ar:"الكافيتيريا",           type:"noun",    example:"Wir treffen uns in der Cafeteria." },

  // ── CHAPTER 3: Was kostet das ─────────────────────────────
  { id:53, ch:3, de:"kosten",          ar:"يكلّف / يُساوي",         type:"verb",    example:"Was kostet das?" },
  { id:54, ch:3, de:"kaufen",          ar:"يشتري",                 type:"verb",    example:"Ich kaufe einen Laptop." },
  { id:55, ch:3, de:"teuer",           ar:"غالي",                  type:"adj",     example:"Das ist zu teuer!" },
  { id:56, ch:3, de:"billig",          ar:"رخيص",                  type:"adj",     example:"Das ist sehr billig!" },
  { id:57, ch:3, de:"der Euro",        ar:"اليورو",                type:"noun",    example:"Das kostet 10 Euro." },
  { id:58, ch:3, de:"der Cent",        ar:"السنت",                 type:"noun",    example:"50 Cent." },
  { id:59, ch:3, de:"der Laptop",      ar:"الحاسوب المحمول",        type:"noun",    example:"Der Laptop kostet 599 Euro." },
  { id:60, ch:3, de:"das Handy",       ar:"الهاتف الجوال",          type:"noun",    example:"Mein Handy ist neu." },
  { id:61, ch:3, de:"das Buch",        ar:"الكتاب",                type:"noun",    example:"Das Buch kostet 15 Euro." },
  { id:62, ch:3, de:"die Uhr",         ar:"الساعة",                type:"noun",    example:"Die Uhr ist schön." },
  { id:63, ch:3, de:"nehmen",          ar:"يأخذ",                  type:"verb",    example:"Ich nehme den Laptop." },
  { id:64, ch:3, de:"der Artikel",     ar:"أداة التعريف",           type:"grammar", example:"der, die, das" },
  { id:65, ch:3, de:"ein / eine",      ar:"أداة التنكير",           type:"grammar", example:"ein Mann, eine Frau" },
  { id:66, ch:3, de:"kein / keine",    ar:"لا يوجد",               type:"grammar", example:"Ich habe keine Zeit." },
  { id:67, ch:3, de:"der Flohmarkt",   ar:"سوق البضائع المستعملة",  type:"noun",    example:"Am Samstag ist Flohmarkt." },
  { id:68, ch:3, de:"der Supermarkt",  ar:"السوبرماركت",           type:"noun",    example:"Ich gehe in den Supermarkt." },
  { id:69, ch:3, de:"schön",           ar:"جميل",                  type:"adj",     example:"Das Kleid ist schön." },
  { id:70, ch:3, de:"groß",            ar:"كبير",                  type:"adj",     example:"Die Wohnung ist groß." },
  { id:71, ch:3, de:"klein",           ar:"صغير",                  type:"adj",     example:"Das Kind ist klein." },
  { id:72, ch:3, de:"neu",             ar:"جديد",                  type:"adj",     example:"Das Handy ist neu." },
  { id:73, ch:3, de:"alt",             ar:"قديم / كبير السن",        type:"adj",     example:"Das Buch ist alt." },

  // ── CHAPTER 4: Wie spät ist es ────────────────────────────
  { id:74, ch:4, de:"Wie spät ist es?", ar:"كم الساعة؟",           type:"phrase",  example:"Entschuldigung, wie spät ist es?" },
  { id:75, ch:4, de:"Es ist ... Uhr",   ar:"الساعة ...",            type:"phrase",  example:"Es ist 9 Uhr." },
  { id:76, ch:4, de:"halb",             ar:"النصف",                 type:"time",    example:"halb drei = الساعة 2:30" },
  { id:77, ch:4, de:"Viertel nach",     ar:"والربع",                type:"time",    example:"Viertel nach neun = 9:15" },
  { id:78, ch:4, de:"Viertel vor",      ar:"إلا الربع",             type:"time",    example:"Viertel vor zehn = 9:45" },
  { id:79, ch:4, de:"der Montag",       ar:"الاثنين",               type:"noun",    example:"Am Montag habe ich Kurs." },
  { id:80, ch:4, de:"der Dienstag",     ar:"الثلاثاء",              type:"noun",    example:"Dienstag ist frei." },
  { id:81, ch:4, de:"der Mittwoch",     ar:"الأربعاء",              type:"noun",    example:"Mittwoch nachmittag." },
  { id:82, ch:4, de:"der Donnerstag",   ar:"الخميس",                type:"noun",    example:"Donnerstag abend." },
  { id:83, ch:4, de:"der Freitag",      ar:"الجمعة",                type:"noun",    example:"Freitag ist Wochenende." },
  { id:84, ch:4, de:"das Wochenende",   ar:"عطلة الأسبوع",          type:"noun",    example:"Am Wochenende schlafe ich." },
  { id:85, ch:4, de:"aufstehen",        ar:"يستيقظ / يقوم",          type:"verb",    example:"Ich stehe um 7 Uhr auf." },
  { id:86, ch:4, de:"frühstücken",      ar:"يتناول الفطور",         type:"verb",    example:"Ich frühstücke um 8 Uhr." },
  { id:87, ch:4, de:"anfangen",         ar:"يبدأ",                  type:"verb",    example:"Der Kurs fängt um 9 an." },
  { id:88, ch:4, de:"der Termin",       ar:"الموعد",                type:"noun",    example:"Ich habe einen Termin." },
  { id:89, ch:4, de:"der Morgen",       ar:"الصباح",                type:"noun",    example:"Guten Morgen!" },
  { id:90, ch:4, de:"der Abend",        ar:"المساء",                type:"noun",    example:"Guten Abend!" },
  { id:91, ch:4, de:"die Nacht",        ar:"الليل",                 type:"noun",    example:"Gute Nacht!" },

  // ── CHAPTER 5: Einkaufen ──────────────────────────────────
  { id:92, ch:5, de:"das Brot",         ar:"الخبز",                 type:"noun",    example:"Ich kaufe ein Kilo Brot." },
  { id:93, ch:5, de:"die Tomate",       ar:"الطماطم",               type:"noun",    example:"500 Gramm Tomaten." },
  { id:94, ch:5, de:"der Käse",         ar:"الجبن",                 type:"noun",    example:"Käse und Brot." },
  { id:95, ch:5, de:"das Fleisch",      ar:"اللحم",                 type:"noun",    example:"Ich esse kein Fleisch." },
  { id:96, ch:5, de:"das Obst",         ar:"الفاكهة",               type:"noun",    example:"Obst ist gesund." },
  { id:97, ch:5, de:"das Gemüse",       ar:"الخضروات",              type:"noun",    example:"Viel Gemüse essen." },
  { id:98, ch:5, de:"die Zwiebel",      ar:"البصل",                 type:"noun",    example:"Eine Zwiebel." },
  { id:99, ch:5, de:"die Gurke",        ar:"الخيار",                type:"noun",    example:"Eine Gurke für den Salat." },
  { id:100,ch:5, de:"das Öl",           ar:"الزيت",                 type:"noun",    example:"Öl und Salz." },
  { id:101,ch:5, de:"das Salz",         ar:"الملح",                 type:"noun",    example:"Salz und Pfeffer." },
  { id:102,ch:5, de:"das Kilo",         ar:"الكيلو",                type:"noun",    example:"Ein Kilo Tomaten." },
  { id:103,ch:5, de:"das Gramm",        ar:"الغرام",                type:"noun",    example:"500 Gramm Käse." },
  { id:104,ch:5, de:"der Liter",        ar:"اللتر",                 type:"noun",    example:"Ein Liter Milch." },
  { id:105,ch:5, de:"die Flasche",      ar:"الزجاجة / القنينة",      type:"noun",    example:"Eine Flasche Wasser." },
  { id:106,ch:5, de:"brauchen",         ar:"يحتاج",                 type:"verb",    example:"Ich brauche Brot und Milch." },
  { id:107,ch:5, de:"kochen",           ar:"يطبخ",                  type:"verb",    example:"Ich koche heute Abend." },
  { id:108,ch:5, de:"essen",            ar:"يأكل",                  type:"verb",    example:"Was essen Sie gern?" },
  { id:109,ch:5, de:"lecker",           ar:"لذيذ",                  type:"adj",     example:"Das Essen ist sehr lecker!" },
  { id:110,ch:5, de:"das Rezept",       ar:"الوصفة",                type:"noun",    example:"Das Rezept ist einfach." },
  { id:111,ch:5, de:"Guten Appetit!",   ar:"بالهناء والشفاء!",       type:"phrase",  example:"Das Essen ist fertig. Guten Appetit!" },

  // ── CHAPTER 6: Familie ────────────────────────────────────
  { id:112,ch:6, de:"die Familie",      ar:"العائلة",               type:"noun",    example:"Meine Familie ist groß." },
  { id:113,ch:6, de:"der Vater",        ar:"الأب",                  type:"noun",    example:"Mein Vater heißt Peter." },
  { id:114,ch:6, de:"die Mutter",       ar:"الأم",                  type:"noun",    example:"Meine Mutter ist Ärztin." },
  { id:115,ch:6, de:"der Bruder",       ar:"الأخ",                  type:"noun",    example:"Ich habe einen Bruder." },
  { id:116,ch:6, de:"die Schwester",    ar:"الأخت",                 type:"noun",    example:"Meine Schwester ist 20 Jahre alt." },
  { id:117,ch:6, de:"der Sohn",         ar:"الابن",                 type:"noun",    example:"Mein Sohn heißt Tom." },
  { id:118,ch:6, de:"die Tochter",      ar:"الابنة",                type:"noun",    example:"Ich habe eine Tochter." },
  { id:119,ch:6, de:"der Großvater",    ar:"الجد",                  type:"noun",    example:"Mein Großvater ist 80 Jahre alt." },
  { id:120,ch:6, de:"die Großmutter",   ar:"الجدة",                 type:"noun",    example:"Die Großmutter kocht gut." },
  { id:121,ch:6, de:"das Kind",         ar:"الطفل",                 type:"noun",    example:"Ich habe zwei Kinder." },
  { id:122,ch:6, de:"der Geburtstag",   ar:"عيد الميلاد",           type:"noun",    example:"Heute ist mein Geburtstag!" },
  { id:123,ch:6, de:"Herzlichen Glückwunsch!", ar:"كل عام وأنت بخير! / مبروك!", type:"phrase", example:"Herzlichen Glückwunsch zum Geburtstag!" },
  { id:124,ch:6, de:"alt sein",         ar:"يبلغ من العمر",          type:"phrase",  example:"Ich bin 25 Jahre alt." },
  { id:125,ch:6, de:"das Foto",         ar:"الصورة",                type:"noun",    example:"Das ist ein Familienfoto." },

  // ── CHAPTER 7: Wohnen ─────────────────────────────────────
  { id:126,ch:7, de:"die Wohnung",      ar:"الشقة",                 type:"noun",    example:"Ich wohne in einer Wohnung." },
  { id:127,ch:7, de:"das Haus",         ar:"المنزل / البيت",         type:"noun",    example:"Das Haus ist groß." },
  { id:128,ch:7, de:"das Zimmer",       ar:"الغرفة",                type:"noun",    example:"Die Wohnung hat 3 Zimmer." },
  { id:129,ch:7, de:"das Wohnzimmer",   ar:"غرفة المعيشة",          type:"noun",    example:"Im Wohnzimmer gibt es ein Sofa." },
  { id:130,ch:7, de:"das Schlafzimmer", ar:"غرفة النوم",            type:"noun",    example:"Das Schlafzimmer ist ruhig." },
  { id:131,ch:7, de:"die Küche",        ar:"المطبخ",                type:"noun",    example:"Ich koche in der Küche." },
  { id:132,ch:7, de:"das Bad/Badezimmer",ar:"الحمام",               type:"noun",    example:"Das Bad hat eine Dusche." },
  { id:133,ch:7, de:"die Miete",        ar:"الإيجار",               type:"noun",    example:"Die Miete kostet 800 Euro." },
  { id:134,ch:7, de:"der Stock / die Etage",ar:"الطابق",            type:"noun",    example:"Im 3. Stock." },
  { id:135,ch:7, de:"das Sofa",         ar:"الأريكة",               type:"noun",    example:"Das Sofa ist bequem." },
  { id:136,ch:7, de:"der Schrank",      ar:"الخزانة",               type:"noun",    example:"Der Schrank ist groß." },
  { id:137,ch:7, de:"das Bett",         ar:"السرير",                type:"noun",    example:"Das Bett ist neu." },
  { id:138,ch:7, de:"der Tisch",        ar:"الطاولة",               type:"noun",    example:"Der Tisch ist aus Holz." },
  { id:139,ch:7, de:"der Stuhl",        ar:"الكرسي",                type:"noun",    example:"Nehmen Sie Platz!" },
  { id:140,ch:7, de:"auf",              ar:"على",                   type:"prep",    example:"Das Buch ist auf dem Tisch." },
  { id:141,ch:7, de:"neben",            ar:"بجانب",                 type:"prep",    example:"Die Lampe ist neben dem Sofa." },
  { id:142,ch:7, de:"vor",              ar:"أمام",                  type:"prep",    example:"Der Schrank steht vor dem Fenster." },
  { id:143,ch:7, de:"hinter",           ar:"خلف",                   type:"prep",    example:"Das Bild ist hinter dem Sofa." },

  // ── CHAPTER 8: Gesundheit ─────────────────────────────────
  { id:144,ch:8, de:"der Kopf",         ar:"الرأس",                 type:"noun",    example:"Mein Kopf tut weh." },
  { id:145,ch:8, de:"der Bauch",        ar:"البطن",                 type:"noun",    example:"Ich habe Bauchschmerzen." },
  { id:146,ch:8, de:"der Hals",         ar:"الحلق / الرقبة",         type:"noun",    example:"Mein Hals tut weh." },
  { id:147,ch:8, de:"der Rücken",       ar:"الظهر",                 type:"noun",    example:"Rückenschmerzen." },
  { id:148,ch:8, de:"Kopfschmerzen",    ar:"صداع الرأس",            type:"noun",    example:"Ich habe Kopfschmerzen." },
  { id:149,ch:8, de:"das Fieber",       ar:"الحمى / السخونة",        type:"noun",    example:"Ich habe Fieber." },
  { id:150,ch:8, de:"die Erkältung",    ar:"البرد / الرشح",          type:"noun",    example:"Ich habe eine Erkältung." },
  { id:151,ch:8, de:"der Arzt / die Ärztin",ar:"الطبيب / الطبيبة",  type:"noun",    example:"Ich gehe zum Arzt." },
  { id:152,ch:8, de:"das Krankenhaus",  ar:"المستشفى",              type:"noun",    example:"Sie arbeitet im Krankenhaus." },
  { id:153,ch:8, de:"das Medikament",   ar:"الدواء",                type:"noun",    example:"Nehmen Sie Medikamente." },
  { id:154,ch:8, de:"müssen",           ar:"يجب",                   type:"verb",    example:"Ich muss zum Arzt gehen." },
  { id:155,ch:8, de:"können",           ar:"يستطيع / يمكن",          type:"verb",    example:"Ich kann nicht kommen." },
  { id:156,ch:8, de:"dürfen",           ar:"يجوز / مسموح",           type:"verb",    example:"Man darf nicht rauchen." },
  { id:157,ch:8, de:"wehtun",           ar:"يؤلم",                  type:"verb",    example:"Mein Kopf tut weh." },
  { id:158,ch:8, de:"gesund",           ar:"بصحة جيدة / صحي",        type:"adj",     example:"Sport ist gesund." },
  { id:159,ch:8, de:"der Sport",        ar:"الرياضة",               type:"noun",    example:"Ich mache gern Sport." },

  // ── CHAPTER 9: Unterwegs ──────────────────────────────────
  { id:160,ch:9, de:"der Zug",          ar:"القطار",                type:"noun",    example:"Der Zug fährt um 10 Uhr ab." },
  { id:161,ch:9, de:"das Auto",         ar:"السيارة",               type:"noun",    example:"Ich fahre mit dem Auto." },
  { id:162,ch:9, de:"das Fahrrad",      ar:"الدراجة",               type:"noun",    example:"Ich fahre gern Fahrrad." },
  { id:163,ch:9, de:"die U-Bahn",       ar:"مترو الأنفاق",           type:"noun",    example:"Nehmen Sie die U-Bahn." },
  { id:164,ch:9, de:"der Bus",          ar:"الحافلة",               type:"noun",    example:"Der Bus fährt alle 10 Minuten." },
  { id:165,ch:9, de:"die Fahrkarte",    ar:"التذكرة",               type:"noun",    example:"Eine Fahrkarte nach Berlin." },
  { id:166,ch:9, de:"der Bahnhof",      ar:"محطة القطار",           type:"noun",    example:"Der Bahnhof ist groß." },
  { id:167,ch:9, de:"das Gleis",        ar:"الرصيف / السكة",         type:"noun",    example:"Gleis 7." },
  { id:168,ch:9, de:"abfahren",         ar:"يغادر / يقلع",           type:"verb",    example:"Der Zug fährt um 10 ab." },
  { id:169,ch:9, de:"ankommen",         ar:"يصل",                   type:"verb",    example:"Der Zug kommt um 14 Uhr an." },
  { id:170,ch:9, de:"geradeaus",        ar:"إلى الأمام مباشرة",      type:"adv",     example:"Gehen Sie geradeaus." },
  { id:171,ch:9, de:"rechts",           ar:"يميناً",                 type:"adv",     example:"Biegen Sie rechts ab." },
  { id:172,ch:9, de:"links",            ar:"يساراً",                 type:"adv",     example:"Die nächste Straße links." },
  { id:173,ch:9, de:"hin und zurück",   ar:"ذهاباً وعودة",           type:"phrase",  example:"Eine Fahrkarte hin und zurück." },

  // ── CHAPTER 10: Freizeit ──────────────────────────────────
  { id:174,ch:10,de:"das Hobby",        ar:"الهواية",               type:"noun",    example:"Was ist dein Hobby?" },
  { id:175,ch:10,de:"der Fußball",      ar:"كرة القدم",             type:"noun",    example:"Ich spiele gern Fußball." },
  { id:176,ch:10,de:"das Tennis",       ar:"التنس",                 type:"noun",    example:"Spielst du Tennis?" },
  { id:177,ch:10,de:"das Schwimmen",    ar:"السباحة",               type:"noun",    example:"Schwimmen ist gesund." },
  { id:178,ch:10,de:"die Musik",        ar:"الموسيقى",              type:"noun",    example:"Ich höre gern Musik." },
  { id:179,ch:10,de:"lesen",            ar:"يقرأ",                  type:"verb",    example:"Ich lese gern Bücher." },
  { id:180,ch:10,de:"spielen",          ar:"يلعب",                  type:"verb",    example:"Ich spiele Gitarre." },
  { id:181,ch:10,de:"hören",            ar:"يسمع / يستمع",           type:"verb",    example:"Ich höre Musik." },
  { id:182,ch:10,de:"gern",             ar:"يحب / بسرور",            type:"adv",     example:"Ich spiele gern Fußball." },
  { id:183,ch:10,de:"nicht gern",       ar:"لا يحب",                type:"phrase",  example:"Ich lese nicht gern." },
  { id:184,ch:10,de:"der Spaß",         ar:"المتعة / المرح",         type:"noun",    example:"Das macht Spaß!" },
  { id:185,ch:10,de:"das Kino",         ar:"السينما",               type:"noun",    example:"Gehen wir ins Kino?" },
  { id:186,ch:10,de:"das Konzert",      ar:"الحفلة الموسيقية",       type:"noun",    example:"Morgen ist ein Konzert." },
  { id:187,ch:10,de:"die Einladung",    ar:"الدعوة",                type:"noun",    example:"Ich habe eine Einladung." },

  // ── CHAPTER 11: Arbeit ────────────────────────────────────
  { id:188,ch:11,de:"die Arbeit / der Job",ar:"العمل / الوظيفة",    type:"noun",    example:"Ich suche Arbeit." },
  { id:189,ch:11,de:"der Beruf",        ar:"المهنة / الحرفة",        type:"noun",    example:"Was sind Sie von Beruf?" },
  { id:190,ch:11,de:"der Arzt",         ar:"الطبيب",                type:"noun",    example:"Ich bin Arzt." },
  { id:191,ch:11,de:"der Lehrer",       ar:"المعلم",                type:"noun",    example:"Er ist Lehrer." },
  { id:192,ch:11,de:"der Ingenieur",    ar:"المهندس",               type:"noun",    example:"Ich bin Ingenieur." },
  { id:193,ch:11,de:"der Koch",         ar:"الطباخ",                type:"noun",    example:"Der Koch kocht gut." },
  { id:194,ch:11,de:"der Verkäufer",    ar:"البائع",                type:"noun",    example:"Der Verkäufer ist freundlich." },
  { id:195,ch:11,de:"das Büro",         ar:"المكتب",                type:"noun",    example:"Ich arbeite im Büro." },
  { id:196,ch:11,de:"arbeiten",         ar:"يعمل",                  type:"verb",    example:"Ich arbeite 40 Stunden." },
  { id:197,ch:11,de:"das Gehalt",       ar:"الراتب",                type:"noun",    example:"Das Gehalt ist 2500 Euro." },
  { id:198,ch:11,de:"die Stunde",       ar:"الساعة (وحدة زمن)",      type:"noun",    example:"40 Stunden pro Woche." },

  // ── CHAPTER 12: Restaurant ────────────────────────────────
  { id:199,ch:12,de:"das Restaurant",   ar:"المطعم",                type:"noun",    example:"Wir gehen ins Restaurant." },
  { id:200,ch:12,de:"die Speisekarte",  ar:"قائمة الطعام",          type:"noun",    example:"Die Speisekarte, bitte!" },
  { id:201,ch:12,de:"der Kellner",      ar:"النادل",                type:"noun",    example:"Der Kellner ist freundlich." },
  { id:202,ch:12,de:"die Vorspeise",    ar:"المقبلات",              type:"noun",    example:"Als Vorspeise möchte ich Suppe." },
  { id:203,ch:12,de:"die Hauptspeise",  ar:"الطبق الرئيسي",          type:"noun",    example:"Als Hauptspeise das Schnitzel." },
  { id:204,ch:12,de:"das Dessert",      ar:"الحلوى",                type:"noun",    example:"Als Dessert ein Eis." },
  { id:205,ch:12,de:"das Schnitzel",    ar:"الشنيتزل (قطعة لحم مقلية)",type:"noun", example:"Das Schnitzel ist lecker." },
  { id:206,ch:12,de:"die Suppe",        ar:"الشوربة",               type:"noun",    example:"Eine Tomatensuppe, bitte." },
  { id:207,ch:12,de:"bestellen",        ar:"يطلب (في المطعم)",       type:"verb",    example:"Was möchten Sie bestellen?" },
  { id:208,ch:12,de:"Zahlen, bitte!",   ar:"الحساب من فضلك!",        type:"phrase",  example:"Entschuldigung! Zahlen, bitte!" },
  { id:209,ch:12,de:"Stimmt so.",       ar:"احتفظ بالباقي. (عند الدفع)", type:"phrase",example:"Stimmt so. Das ist für Sie." },
  { id:210,ch:12,de:"das Trinkgeld",    ar:"البقشيش / الإكرامية",    type:"noun",    example:"Ich gebe Trinkgeld." },

  // ── USEFUL EXTRAS ─────────────────────────────────────────
  { id:211,ch:1, de:"ja",              ar:"نعم",                   type:"phrase",  example:"Ja, ich komme aus Berlin." },
  { id:212,ch:1, de:"nein",            ar:"لا",                    type:"phrase",  example:"Nein, ich wohne nicht in Berlin." },
  { id:213,ch:1, de:"und",             ar:"و",                     type:"phrase",  example:"Ich bin müde und krank." },
  { id:214,ch:1, de:"oder",            ar:"أو",                    type:"phrase",  example:"Kaffee oder Tee?" },
  { id:215,ch:1, de:"aber",            ar:"لكن",                   type:"phrase",  example:"Das ist teuer, aber schön." },
  { id:216,ch:2, de:"sehr",            ar:"جداً",                  type:"adv",     example:"Das ist sehr lecker!" },
  { id:217,ch:1, de:"auch",            ar:"أيضاً",                 type:"adv",     example:"Ich spreche auch Englisch." },
  { id:218,ch:1, de:"nicht",           ar:"لا / ليس",              type:"adv",     example:"Das ist nicht gut." },
  { id:219,ch:1, de:"viel",            ar:"كثير",                  type:"adv",     example:"Ich lerne viel." },
  { id:220,ch:2, de:"heute",           ar:"اليوم",                 type:"adv",     example:"Heute ist Montag." },
  { id:221,ch:2, de:"morgen",          ar:"غداً",                  type:"adv",     example:"Morgen habe ich Kurs." },
  { id:222,ch:4, de:"jetzt",           ar:"الآن",                  type:"adv",     example:"Was machen Sie jetzt?" },
  { id:223,ch:4, de:"dann",            ar:"ثم / بعدها",             type:"adv",     example:"Ich frühstücke, dann gehe ich." },
  { id:224,ch:1, de:"Entschuldigung!", ar:"عذراً! / معذرة!",        type:"phrase",  example:"Entschuldigung! Wie spät ist es?" },
  { id:225,ch:1, de:"noch einmal",     ar:"مرة أخرى",              type:"phrase",  example:"Sagen Sie das noch einmal, bitte." }
];

// Type labels for display
const TYPE_LABELS = {
  noun:    { ar: "اسم",    de: "Nomen",      color: "#4f8ef7" },
  verb:    { ar: "فعل",    de: "Verb",       color: "#f59e0b" },
  adj:     { ar: "صفة",    de: "Adjektiv",   color: "#34d399" },
  phrase:  { ar: "عبارة",  de: "Ausdruck",   color: "#a78bfa" },
  pronoun: { ar: "ضمير",   de: "Pronomen",   color: "#60a5fa" },
  number:  { ar: "رقم",    de: "Zahl",       color: "#fbbf24" },
  grammar: { ar: "قاعدة",  de: "Grammatik",  color: "#f87171" },
  adv:     { ar: "ظرف",    de: "Adverb",     color: "#34d399" },
  prep:    { ar: "حرف جر", de: "Präposition",color: "#fb923c" },
  time:    { ar: "وقت",    de: "Zeit",       color: "#a78bfa" }
};
