// ============================================================
// VOCABULARY DATABASE - Complete A1 Vocabulary (Multilingual)
// Berliner Platz 1 Neu - All 12 Chapters
// ============================================================

const VOCABULARY = [
  {
    "id": 1,
    "ch": 1,
    "de": "Hallo",
    "ar": "مرحباً",
    "type": "phrase",
    "example": "Hallo! Ich bin Maria.",
    "en": "Hello",
    "tr": "Merhaba",
    "ro": "Bună",
    "bs": "Zdravo"
  },
  {
    "id": 2,
    "ch": 1,
    "de": "Guten Tag",
    "ar": "مرحباً / صباح الخير",
    "type": "phrase",
    "example": "Guten Tag! Wie heißen Sie?",
    "en": "Good day / Hello",
    "tr": "İyi günler / Merhaba",
    "ro": "Bună ziua",
    "bs": "Dobar dan / Zdravo"
  },
  {
    "id": 3,
    "ch": 1,
    "de": "Guten Morgen",
    "ar": "صباح الخير",
    "type": "phrase",
    "example": "Guten Morgen, Frau Kohl!",
    "en": "Good morning",
    "tr": "Günaydın",
    "ro": "Bună dimineața",
    "bs": "Dobro jutro"
  },
  {
    "id": 4,
    "ch": 1,
    "de": "Guten Abend",
    "ar": "مساء الخير",
    "type": "phrase",
    "example": "Guten Abend!",
    "en": "Good evening",
    "tr": "İyi akşamlar",
    "ro": "Bună seara",
    "bs": "Dobro veče"
  },
  {
    "id": 5,
    "ch": 1,
    "de": "Auf Wiedersehen",
    "ar": "مع السلامة (رسمي)",
    "type": "phrase",
    "example": "Auf Wiedersehen! Tschüss!",
    "en": "Goodbye (formal)",
    "tr": "Görüşmek üzere (resmi)",
    "ro": "La revedere (formal)",
    "bs": "doviđenja (formalno)"
  },
  {
    "id": 6,
    "ch": 1,
    "de": "Tschüss",
    "ar": "مع السلامة (غير رسمي)",
    "type": "phrase",
    "example": "Tschüss! Bis morgen!",
    "en": "Goodbye (informal)",
    "tr": "Görüşürüz / Hoşça kal",
    "ro": "Pa (informal)",
    "bs": "zbogom (neformalno)"
  },
  {
    "id": 7,
    "ch": 1,
    "de": "Bitte",
    "ar": "من فضلك / عفواً",
    "type": "phrase",
    "example": "Buchstabieren Sie bitte.",
    "en": "Please / You're welcome",
    "tr": "Lütfen / Rica ederim",
    "ro": "Te rog / Cu plăcere",
    "bs": "Molim / Nema na čemu"
  },
  {
    "id": 8,
    "ch": 1,
    "de": "Danke",
    "ar": "شكراً",
    "type": "phrase",
    "example": "Danke schön!",
    "en": "Thank you",
    "tr": "Teşekkürler",
    "ro": "Mulțumesc",
    "bs": "Hvala ti"
  },
  {
    "id": 9,
    "ch": 1,
    "de": "der Name",
    "ar": "الاسم",
    "type": "noun",
    "example": "Wie ist Ihr Name?",
    "en": "the name",
    "tr": "isim / ad",
    "ro": "numele",
    "bs": "ime"
  },
  {
    "id": 10,
    "ch": 1,
    "de": "heißen",
    "ar": "يُسمّى / اسمه",
    "type": "verb",
    "example": "Ich heiße Maria.",
    "en": "to be called",
    "tr": "adlandırılmak / adı olmak",
    "ro": "a se numi",
    "bs": "biti pozvan"
  },
  {
    "id": 11,
    "ch": 1,
    "de": "sein",
    "ar": "يكون / يوجد",
    "type": "verb",
    "example": "Ich bin Carlos.",
    "en": "to be",
    "tr": "olmak",
    "ro": "a fi",
    "bs": "biti"
  },
  {
    "id": 12,
    "ch": 1,
    "de": "kommen",
    "ar": "يأتي",
    "type": "verb",
    "example": "Woher kommen Sie?",
    "en": "to come",
    "tr": "gelmek",
    "ro": "a veni",
    "bs": "doći"
  },
  {
    "id": 13,
    "ch": 1,
    "de": "wohnen",
    "ar": "يسكن / يقطن",
    "type": "verb",
    "example": "Ich wohne in Berlin.",
    "en": "to live / reside",
    "tr": "yaşamak / ikamet etmek",
    "ro": "a locui",
    "bs": "živjeti / boraviti"
  },
  {
    "id": 14,
    "ch": 1,
    "de": "sprechen",
    "ar": "يتحدث / يتكلم",
    "type": "verb",
    "example": "Ich spreche Arabisch und Deutsch.",
    "en": "to speak",
    "tr": "konuşmak",
    "ro": "a vorbi",
    "bs": "govoriti"
  },
  {
    "id": 15,
    "ch": 1,
    "de": "aus Deutschland",
    "ar": "من ألمانيا",
    "type": "phrase",
    "example": "Ich komme aus Deutschland.",
    "en": "from Germany",
    "tr": "Almanya'dan",
    "ro": "din Germania",
    "bs": "iz Njemačke"
  },
  {
    "id": 16,
    "ch": 1,
    "de": "die Sprache",
    "ar": "اللغة",
    "type": "noun",
    "example": "Welche Sprache sprechen Sie?",
    "en": "the language",
    "tr": "dil",
    "ro": "limba",
    "bs": "jezik"
  },
  {
    "id": 17,
    "ch": 1,
    "de": "das Land",
    "ar": "البلد / الدولة",
    "type": "noun",
    "example": "Aus welchem Land kommen Sie?",
    "en": "the country",
    "tr": "ülke",
    "ro": "țara",
    "bs": "zemlji"
  },
  {
    "id": 18,
    "ch": 1,
    "de": "der Kurs",
    "ar": "الدورة / الكورس",
    "type": "noun",
    "example": "Der Deutschkurs beginnt um 9 Uhr.",
    "en": "the course",
    "tr": "kurs",
    "ro": "cursul",
    "bs": "kurs"
  },
  {
    "id": 19,
    "ch": 1,
    "de": "buchstabieren",
    "ar": "يتهجأ",
    "type": "verb",
    "example": "Buchstabieren Sie bitte Ihren Namen.",
    "en": "to spell",
    "tr": "hecelemek",
    "ro": "a silabisi",
    "bs": "spelovati"
  },
  {
    "id": 20,
    "ch": 1,
    "de": "das Alphabet",
    "ar": "الأبجدية",
    "type": "noun",
    "example": "Das deutsche Alphabet hat 26 Buchstaben.",
    "en": "the alphabet",
    "tr": "alfabe",
    "ro": "alfabetul",
    "bs": "abeceda"
  },
  {
    "id": 21,
    "ch": 1,
    "de": "ich",
    "ar": "أنا",
    "type": "pronoun",
    "example": "Ich heiße Carlos.",
    "en": "I",
    "tr": "ben",
    "ro": "eu",
    "bs": "I"
  },
  {
    "id": 22,
    "ch": 1,
    "de": "du",
    "ar": "أنتَ (غير رسمي)",
    "type": "pronoun",
    "example": "Wie heißt du?",
    "en": "you (singular, informal)",
    "tr": "sen",
    "ro": "tu (singular, informal)",
    "bs": "ti (jednina, neformalno)"
  },
  {
    "id": 23,
    "ch": 1,
    "de": "Sie",
    "ar": "حضرتك (رسمي)",
    "type": "pronoun",
    "example": "Wie heißen Sie?",
    "en": "you (formal)",
    "tr": "Siz",
    "ro": "tu (formal)",
    "bs": "ti (formalno)"
  },
  {
    "id": 24,
    "ch": 1,
    "de": "er / sie / es",
    "ar": "هو / هي / إنه",
    "type": "pronoun",
    "example": "Er heißt Thomas.",
    "en": "he / she / it",
    "tr": "o (erkek / kadın / cansız)",
    "ro": "el",
    "bs": "on/ona/to"
  },
  {
    "id": 25,
    "ch": 1,
    "de": "wir",
    "ar": "نحن",
    "type": "pronoun",
    "example": "Wir kommen aus Spanien.",
    "en": "we",
    "tr": "biz",
    "ro": "noi",
    "bs": "mi"
  },
  {
    "id": 26,
    "ch": 2,
    "de": "Wie geht's?",
    "ar": "كيف حالك؟",
    "type": "phrase",
    "example": "Hallo! Wie geht's?",
    "en": "How are you?",
    "tr": "Nasılsın? / Nasıl gidiyor?",
    "ro": "Ce mai faci?",
    "bs": "Kako si?"
  },
  {
    "id": 27,
    "ch": 2,
    "de": "gut",
    "ar": "جيد / بخير",
    "type": "adj",
    "example": "Danke, gut!",
    "en": "good",
    "tr": "iyi",
    "ro": "bun",
    "bs": "dobro"
  },
  {
    "id": 28,
    "ch": 2,
    "de": "nicht gut",
    "ar": "ليس جيداً",
    "type": "phrase",
    "example": "Mir geht es nicht gut.",
    "en": "not good",
    "tr": "iyi değil",
    "ro": "nu e bun",
    "bs": "nije dobro"
  },
  {
    "id": 29,
    "ch": 2,
    "de": "es geht",
    "ar": "لا بأس / يمشي",
    "type": "phrase",
    "example": "Es geht. Ich bin müde.",
    "en": "so-so / it's okay",
    "tr": "şöyle böyle / idare eder",
    "ro": "asa-asa",
    "bs": "tako-tako / u redu je"
  },
  {
    "id": 30,
    "ch": 2,
    "de": "müde",
    "ar": "متعب",
    "type": "adj",
    "example": "Ich bin sehr müde.",
    "en": "tired",
    "tr": "yorgun",
    "ro": "obosit",
    "bs": "umoran"
  },
  {
    "id": 31,
    "ch": 2,
    "de": "krank",
    "ar": "مريض",
    "type": "adj",
    "example": "Ich bin krank.",
    "en": "sick / ill",
    "tr": "hasta",
    "ro": "bolnav",
    "bs": "bolestan / bolestan"
  },
  {
    "id": 32,
    "ch": 2,
    "de": "der Kaffee",
    "ar": "القهوة",
    "type": "noun",
    "example": "Ich trinke einen Kaffee.",
    "en": "the coffee",
    "tr": "kahve",
    "ro": "cafeaua",
    "bs": "kafu"
  },
  {
    "id": 33,
    "ch": 2,
    "de": "der Tee",
    "ar": "الشاي",
    "type": "noun",
    "example": "Möchten Sie Tee?",
    "en": "the tea",
    "tr": "çay",
    "ro": "ceaiul",
    "bs": "čaj"
  },
  {
    "id": 34,
    "ch": 2,
    "de": "das Wasser",
    "ar": "الماء",
    "type": "noun",
    "example": "Ein Wasser, bitte.",
    "en": "the water",
    "tr": "su",
    "ro": "apa",
    "bs": "voda"
  },
  {
    "id": 35,
    "ch": 2,
    "de": "die Milch",
    "ar": "الحليب",
    "type": "noun",
    "example": "Kaffee mit Milch, bitte.",
    "en": "the milk",
    "tr": "süt",
    "ro": "laptele",
    "bs": "mleko"
  },
  {
    "id": 36,
    "ch": 2,
    "de": "trinken",
    "ar": "يشرب",
    "type": "verb",
    "example": "Was möchten Sie trinken?",
    "en": "to drink",
    "tr": "içmek",
    "ro": "a bea",
    "bs": "piti"
  },
  {
    "id": 37,
    "ch": 2,
    "de": "möchten",
    "ar": "يريد / يودّ",
    "type": "verb",
    "example": "Ich möchte einen Kaffee.",
    "en": "would like",
    "tr": "istemek (kibarca)",
    "ro": "ar dori",
    "bs": "voleo bi"
  },
  {
    "id": 38,
    "ch": 2,
    "de": "null",
    "ar": "صفر (0)",
    "type": "number",
    "example": "Die Zahl null.",
    "en": "zero (0)",
    "tr": "sıfır (0)",
    "ro": "zero (0)",
    "bs": "nula (0)"
  },
  {
    "id": 39,
    "ch": 2,
    "de": "eins",
    "ar": "واحد (1)",
    "type": "number",
    "example": "Eins, zwei, drei...",
    "en": "one (1)",
    "tr": "bir (1)",
    "ro": "unul (1)",
    "bs": "jedan (1)"
  },
  {
    "id": 40,
    "ch": 2,
    "de": "zwei",
    "ar": "اثنان (2)",
    "type": "number",
    "example": "Ich habe zwei Kinder.",
    "en": "two (2)",
    "tr": "iki (2)",
    "ro": "doi (2)",
    "bs": "dva (2)"
  },
  {
    "id": 41,
    "ch": 2,
    "de": "drei",
    "ar": "ثلاثة (3)",
    "type": "number",
    "example": "Drei Euro, bitte.",
    "en": "three (3)",
    "tr": "üç (3)",
    "ro": "trei (3)",
    "bs": "tri (3)"
  },
  {
    "id": 42,
    "ch": 2,
    "de": "vier",
    "ar": "أربعة (4)",
    "type": "number",
    "example": "Vier Personen.",
    "en": "four (4)",
    "tr": "dört (4)",
    "ro": "patru (4)",
    "bs": "četiri (4)"
  },
  {
    "id": 43,
    "ch": 2,
    "de": "fünf",
    "ar": "خمسة (5)",
    "type": "number",
    "example": "Fünf Euro.",
    "en": "five (5)",
    "tr": "beş (5)",
    "ro": "cinci (5)",
    "bs": "pet (5)"
  },
  {
    "id": 44,
    "ch": 2,
    "de": "sechs",
    "ar": "ستة (6)",
    "type": "number",
    "example": "Sechs Uhr.",
    "en": "six (6)",
    "tr": "altı (6)",
    "ro": "șase (6)",
    "bs": "šest (6)"
  },
  {
    "id": 45,
    "ch": 2,
    "de": "sieben",
    "ar": "سبعة (7)",
    "type": "number",
    "example": "Sieben Tage.",
    "en": "seven (7)",
    "tr": "yedi (7)",
    "ro": "sapte (7)",
    "bs": "sedam (7)"
  },
  {
    "id": 46,
    "ch": 2,
    "de": "acht",
    "ar": "ثمانية (8)",
    "type": "number",
    "example": "Acht Stunden.",
    "en": "eight (8)",
    "tr": "sekiz (8)",
    "ro": "opt (8)",
    "bs": "osam (8)"
  },
  {
    "id": 47,
    "ch": 2,
    "de": "neun",
    "ar": "تسعة (9)",
    "type": "number",
    "example": "Neun Uhr.",
    "en": "nine (9)",
    "tr": "dokuz (9)",
    "ro": "nouă (9)",
    "bs": "devet (9)"
  },
  {
    "id": 48,
    "ch": 2,
    "de": "zehn",
    "ar": "عشرة (10)",
    "type": "number",
    "example": "Zehn Euro.",
    "en": "ten (10)",
    "tr": "on (10)",
    "ro": "zece (10)",
    "bs": "deset (10)"
  },
  {
    "id": 49,
    "ch": 2,
    "de": "zwanzig",
    "ar": "عشرون (20)",
    "type": "number",
    "example": "Zwanzig Minuten.",
    "en": "twenty (20)",
    "tr": "yirmi (20)",
    "ro": "douăzeci (20)",
    "bs": "dvadeset (20)"
  },
  {
    "id": 50,
    "ch": 2,
    "de": "hundert",
    "ar": "مئة (100)",
    "type": "number",
    "example": "Hundert Euro.",
    "en": "hundred (100)",
    "tr": "yüz (100)",
    "ro": "suta (100)",
    "bs": "sto (100)"
  },
  {
    "id": 51,
    "ch": 2,
    "de": "die Telefonnummer",
    "ar": "رقم الهاتف",
    "type": "noun",
    "example": "Was ist Ihre Telefonnummer?",
    "en": "the phone number",
    "tr": "telefon numarası",
    "ro": "numărul de telefon",
    "bs": "broj telefona"
  },
  {
    "id": 52,
    "ch": 2,
    "de": "die Cafeteria",
    "ar": "الكافيتيريا",
    "type": "noun",
    "example": "Wir treffen uns in der Cafeteria.",
    "en": "the cafeteria",
    "tr": "kafeterya",
    "ro": "cantina",
    "bs": "kafeterija"
  },
  {
    "id": 53,
    "ch": 3,
    "de": "kosten",
    "ar": "يكلّف / يُساوي",
    "type": "verb",
    "example": "Was kostet das?",
    "en": "to cost",
    "tr": "fiyatı olmak / tutmak",
    "ro": "a costa",
    "bs": "da košta"
  },
  {
    "id": 54,
    "ch": 3,
    "de": "kaufen",
    "ar": "يشتري",
    "type": "verb",
    "example": "Ich kaufe einen Laptop.",
    "en": "to buy",
    "tr": "satın almak",
    "ro": "să cumpere",
    "bs": "kupiti"
  },
  {
    "id": 55,
    "ch": 3,
    "de": "teuer",
    "ar": "غالي",
    "type": "adj",
    "example": "Das ist zu teuer!",
    "en": "expensive",
    "tr": "pahalı",
    "ro": "scump",
    "bs": "skupo"
  },
  {
    "id": 56,
    "ch": 3,
    "de": "billig",
    "ar": "رخيص",
    "type": "adj",
    "example": "Das ist sehr billig!",
    "en": "cheap",
    "tr": "ucuz",
    "ro": "ieftin",
    "bs": "jeftino"
  },
  {
    "id": 57,
    "ch": 3,
    "de": "der Euro",
    "ar": "اليورو",
    "type": "noun",
    "example": "Das kostet 10 Euro.",
    "en": "the Euro",
    "tr": "Euro",
    "ro": "euro",
    "bs": "euro"
  },
  {
    "id": 58,
    "ch": 3,
    "de": "der Cent",
    "ar": "السنت",
    "type": "noun",
    "example": "50 Cent.",
    "en": "the Cent",
    "tr": "Cent",
    "ro": "Centul",
    "bs": "the Cent"
  },
  {
    "id": 59,
    "ch": 3,
    "de": "der Laptop",
    "ar": "الحاسوب المحمول",
    "type": "noun",
    "example": "Der Laptop kostet 599 Euro.",
    "en": "the laptop",
    "tr": "dizüstü bilgisayar",
    "ro": "laptopul",
    "bs": "laptop"
  },
  {
    "id": 60,
    "ch": 3,
    "de": "das Handy",
    "ar": "الهاتف الجوال",
    "type": "noun",
    "example": "Mein Handy ist neu.",
    "en": "the mobile phone",
    "tr": "cep telefonu",
    "ro": "telefonul mobil",
    "bs": "mobilni telefon"
  },
  {
    "id": 61,
    "ch": 3,
    "de": "das Buch",
    "ar": "الكتاب",
    "type": "noun",
    "example": "Das Buch kostet 15 Euro.",
    "en": "the book",
    "tr": "kitap",
    "ro": "cartea",
    "bs": "knjiga"
  },
  {
    "id": 62,
    "ch": 3,
    "de": "die Uhr",
    "ar": "الساعة",
    "type": "noun",
    "example": "Die Uhr ist schön.",
    "en": "the clock / watch",
    "tr": "saat",
    "ro": "ceasul",
    "bs": "sat / sat"
  },
  {
    "id": 63,
    "ch": 3,
    "de": "nehmen",
    "ar": "يأخذ",
    "type": "verb",
    "example": "Ich nehme den Laptop.",
    "en": "to take",
    "tr": "almak",
    "ro": "a lua",
    "bs": "uzeti"
  },
  {
    "id": 64,
    "ch": 3,
    "de": "der Artikel",
    "ar": "أداة التعريف",
    "type": "grammar",
    "example": "der, die, das",
    "en": "the article (grammar)",
    "tr": "artikel (dilbilgisi)",
    "ro": "articolul (gramatica)",
    "bs": "članak (gramatika)"
  },
  {
    "id": 65,
    "ch": 3,
    "de": "ein / eine",
    "ar": "أداة التنكير",
    "type": "grammar",
    "example": "ein Mann, eine Frau",
    "en": "indefinite article",
    "tr": "belirsiz tanımlık (bir)",
    "ro": "articol nedeterminat",
    "bs": "neodređeni član"
  },
  {
    "id": 66,
    "ch": 3,
    "de": "kein / keine",
    "ar": "لا يوجد",
    "type": "grammar",
    "example": "Ich habe keine Zeit.",
    "en": "negation article",
    "tr": "olumsuzluk tanımlığı",
    "ro": "articol de negație",
    "bs": "negacijski članak"
  },
  {
    "id": 67,
    "ch": 3,
    "de": "der Flohmarkt",
    "ar": "سوق البضائع المستعملة",
    "type": "noun",
    "example": "Am Samstag ist Flohmarkt.",
    "en": "the flea market",
    "tr": "bit pazarı",
    "ro": "târgul de vechituri",
    "bs": "buvljak"
  },
  {
    "id": 68,
    "ch": 3,
    "de": "der Supermarkt",
    "ar": "السوبرماركت",
    "type": "noun",
    "example": "Ich gehe in den Supermarkt.",
    "en": "the supermarket",
    "tr": "süpermarket",
    "ro": "supermarketul",
    "bs": "supermarket"
  },
  {
    "id": 69,
    "ch": 3,
    "de": "schön",
    "ar": "جميل",
    "type": "adj",
    "example": "Das Kleid ist schön.",
    "en": "beautiful / nice",
    "tr": "güzel",
    "ro": "frumos",
    "bs": "lijepo / lijepo"
  },
  {
    "id": 70,
    "ch": 3,
    "de": "groß",
    "ar": "كبير",
    "type": "adj",
    "example": "Die Wohnung ist groß.",
    "en": "big / large",
    "tr": "büyük",
    "ro": "mare",
    "bs": "veliki / veliki"
  },
  {
    "id": 71,
    "ch": 3,
    "de": "klein",
    "ar": "صغير",
    "type": "adj",
    "example": "Das Kind ist klein.",
    "en": "small / little",
    "tr": "küçük",
    "ro": "mic",
    "bs": "mali / mali"
  },
  {
    "id": 72,
    "ch": 3,
    "de": "neu",
    "ar": "جديد",
    "type": "adj",
    "example": "Das Handy ist neu.",
    "en": "new",
    "tr": "yeni",
    "ro": "nou",
    "bs": "novo"
  },
  {
    "id": 73,
    "ch": 3,
    "de": "alt",
    "ar": "قديم / كبير السن",
    "type": "adj",
    "example": "Das Buch ist alt.",
    "en": "old",
    "tr": "eski / yaşlı",
    "ro": "vechi",
    "bs": "star"
  },
  {
    "id": 74,
    "ch": 4,
    "de": "Wie spät ist es?",
    "ar": "كم الساعة؟",
    "type": "phrase",
    "example": "Entschuldigung, wie spät ist es?",
    "en": "What time is it?",
    "tr": "Saat kaç?",
    "ro": "Cât este ceasul?",
    "bs": "Koliko je sati?"
  },
  {
    "id": 75,
    "ch": 4,
    "de": "Es ist ... Uhr",
    "ar": "الساعة ...",
    "type": "phrase",
    "example": "Es ist 9 Uhr.",
    "en": "It is ... o'clock",
    "tr": "Saat ...",
    "ro": "Este... ceasul",
    "bs": "Sada je... sat"
  },
  {
    "id": 76,
    "ch": 4,
    "de": "halb",
    "ar": "النصف",
    "type": "time",
    "example": "halb drei = الساعة 2:30",
    "en": "half (time)",
    "tr": "buçuk",
    "ro": "jumatate (timp)",
    "bs": "poluvrijeme (vrijeme)"
  },
  {
    "id": 77,
    "ch": 4,
    "de": "Viertel nach",
    "ar": "والربع",
    "type": "time",
    "example": "Viertel nach neun = 9:15",
    "en": "quarter past",
    "tr": "çeyrek geçe",
    "ro": "un sfert",
    "bs": "prošla četvrt"
  },
  {
    "id": 78,
    "ch": 4,
    "de": "Viertel vor",
    "ar": "إلا الربع",
    "type": "time",
    "example": "Viertel vor zehn = 9:45",
    "en": "quarter to",
    "tr": "çeyrek kala",
    "ro": "sfert la",
    "bs": "quarter to"
  },
  {
    "id": 79,
    "ch": 4,
    "de": "der Montag",
    "ar": "الاثنين",
    "type": "noun",
    "example": "Am Montag habe ich Kurs.",
    "en": "Monday",
    "tr": "Pazartesi",
    "ro": "luni",
    "bs": "ponedjeljak"
  },
  {
    "id": 80,
    "ch": 4,
    "de": "der Dienstag",
    "ar": "الثلاثاء",
    "type": "noun",
    "example": "Dienstag ist frei.",
    "en": "Tuesday",
    "tr": "Salı",
    "ro": "marţi",
    "bs": "utorak"
  },
  {
    "id": 81,
    "ch": 4,
    "de": "der Mittwoch",
    "ar": "الأربعاء",
    "type": "noun",
    "example": "Mittwoch nachmittag.",
    "en": "Wednesday",
    "tr": "Çarşamba",
    "ro": "miercuri",
    "bs": "srijeda"
  },
  {
    "id": 82,
    "ch": 4,
    "de": "der Donnerstag",
    "ar": "الخميس",
    "type": "noun",
    "example": "Donnerstag abend.",
    "en": "Thursday",
    "tr": "Perşembe",
    "ro": "joi",
    "bs": "četvrtak"
  },
  {
    "id": 83,
    "ch": 4,
    "de": "der Freitag",
    "ar": "الجمعة",
    "type": "noun",
    "example": "Freitag ist Wochenende.",
    "en": "Friday",
    "tr": "Cuma",
    "ro": "vineri",
    "bs": "petak"
  },
  {
    "id": 84,
    "ch": 4,
    "de": "das Wochenende",
    "ar": "عطلة الأسبوع",
    "type": "noun",
    "example": "Am Wochenende schlafe ich.",
    "en": "the weekend",
    "tr": "hafta sonu",
    "ro": "weekendul",
    "bs": "vikend"
  },
  {
    "id": 85,
    "ch": 4,
    "de": "aufstehen",
    "ar": "يستيقظ / يقوم",
    "type": "verb",
    "example": "Ich stehe um 7 Uhr auf.",
    "en": "to get up",
    "tr": "ayağa kalkmak / uyanmak",
    "ro": "a se ridica",
    "bs": "da ustanem"
  },
  {
    "id": 86,
    "ch": 4,
    "de": "frühstücken",
    "ar": "يتناول الفطور",
    "type": "verb",
    "example": "Ich frühstücke um 8 Uhr.",
    "en": "to eat breakfast",
    "tr": "kahvaltı yapmak",
    "ro": "a lua micul dejun",
    "bs": "doručkovati"
  },
  {
    "id": 87,
    "ch": 4,
    "de": "anfangen",
    "ar": "يبدأ",
    "type": "verb",
    "example": "Der Kurs fängt um 9 an.",
    "en": "to start / begin",
    "tr": "başlamak",
    "ro": "pentru a începe",
    "bs": "započeti / započeti"
  },
  {
    "id": 88,
    "ch": 4,
    "de": "der Termin",
    "ar": "الموعد",
    "type": "noun",
    "example": "Ich habe einen Termin.",
    "en": "the appointment",
    "tr": "randevu",
    "ro": "programarea / întâlnirea",
    "bs": "imenovanje"
  },
  {
    "id": 89,
    "ch": 4,
    "de": "der Morgen",
    "ar": "الصباح",
    "type": "noun",
    "example": "Guten Morgen!",
    "en": "the morning",
    "tr": "sabah",
    "ro": "dimineața",
    "bs": "jutro"
  },
  {
    "id": 90,
    "ch": 4,
    "de": "der Abend",
    "ar": "المساء",
    "type": "noun",
    "example": "Guten Abend!",
    "en": "the evening",
    "tr": "akşam",
    "ro": "seara",
    "bs": "veče"
  },
  {
    "id": 91,
    "ch": 4,
    "de": "die Nacht",
    "ar": "الليل",
    "type": "noun",
    "example": "Gute Nacht!",
    "en": "the night",
    "tr": "gece",
    "ro": "noaptea",
    "bs": "noć"
  },
  {
    "id": 92,
    "ch": 5,
    "de": "das Brot",
    "ar": "الخبز",
    "type": "noun",
    "example": "Ich kaufe ein Kilo Brot.",
    "en": "the bread",
    "tr": "ekmek",
    "ro": "pâinea",
    "bs": "hleb"
  },
  {
    "id": 93,
    "ch": 5,
    "de": "die Tomate",
    "ar": "الطماطم",
    "type": "noun",
    "example": "500 Gramm Tomaten.",
    "en": "the tomato",
    "tr": "domates",
    "ro": "roșia",
    "bs": "paradajz"
  },
  {
    "id": 94,
    "ch": 5,
    "de": "der Käse",
    "ar": "الجبن",
    "type": "noun",
    "example": "Käse und Brot.",
    "en": "the cheese",
    "tr": "peynir",
    "ro": "brânza",
    "bs": "sir"
  },
  {
    "id": 95,
    "ch": 5,
    "de": "das Fleisch",
    "ar": "اللحم",
    "type": "noun",
    "example": "Ich esse kein Fleisch.",
    "en": "the meat",
    "tr": "et",
    "ro": "carnea",
    "bs": "meso"
  },
  {
    "id": 96,
    "ch": 5,
    "de": "das Obst",
    "ar": "الفاكهة",
    "type": "noun",
    "example": "Obst ist gesund.",
    "en": "the fruit",
    "tr": "meyve",
    "ro": "fructul",
    "bs": "voće"
  },
  {
    "id": 97,
    "ch": 5,
    "de": "das Gemüse",
    "ar": "الخضروات",
    "type": "noun",
    "example": "Viel Gemüse essen.",
    "en": "the vegetable",
    "tr": "sebze",
    "ro": "leguma",
    "bs": "povrće"
  },
  {
    "id": 98,
    "ch": 5,
    "de": "die Zwiebel",
    "ar": "البصل",
    "type": "noun",
    "example": "Eine Zwiebel.",
    "en": "the onion",
    "tr": "soğan",
    "ro": "ceapa",
    "bs": "luk"
  },
  {
    "id": 99,
    "ch": 5,
    "de": "die Gurke",
    "ar": "الخيار",
    "type": "noun",
    "example": "Eine Gurke für den Salat.",
    "en": "the cucumber",
    "tr": "salatalık",
    "ro": "castravetele",
    "bs": "krastavac"
  },
  {
    "id": 100,
    "ch": 5,
    "de": "das Öl",
    "ar": "الزيت",
    "type": "noun",
    "example": "Öl und Salz.",
    "en": "the oil",
    "tr": "sıvı yağ",
    "ro": "uleiul",
    "bs": "ulje"
  },
  {
    "id": 101,
    "ch": 5,
    "de": "das Salz",
    "ar": "الملح",
    "type": "noun",
    "example": "Salz und Pfeffer.",
    "en": "the salt",
    "tr": "tuz",
    "ro": "sarea",
    "bs": "so"
  },
  {
    "id": 102,
    "ch": 5,
    "de": "das Kilo",
    "ar": "الكيلو",
    "type": "noun",
    "example": "Ein Kilo Tomaten.",
    "en": "the kilo",
    "tr": "kilo",
    "ro": "kilogramul",
    "bs": "kilogram"
  },
  {
    "id": 103,
    "ch": 5,
    "de": "das Gramm",
    "ar": "الغرام",
    "type": "noun",
    "example": "500 Gramm Käse.",
    "en": "the gram",
    "tr": "gram",
    "ro": "gramul",
    "bs": "gram"
  },
  {
    "id": 104,
    "ch": 5,
    "de": "der Liter",
    "ar": "اللتر",
    "type": "noun",
    "example": "Ein Liter Milch.",
    "en": "the liter",
    "tr": "litre",
    "ro": "litrul",
    "bs": "litar"
  },
  {
    "id": 105,
    "ch": 5,
    "de": "die Flasche",
    "ar": "الزجاجة / القنينة",
    "type": "noun",
    "example": "Eine Flasche Wasser.",
    "en": "the bottle",
    "tr": "şişe",
    "ro": "sticla",
    "bs": "bocu"
  },
  {
    "id": 106,
    "ch": 5,
    "de": "brauchen",
    "ar": "يحتاج",
    "type": "verb",
    "example": "Ich brauche Brot und Milch.",
    "en": "to need",
    "tr": "ihtiyacı olmak",
    "ro": "a avea nevoie",
    "bs": "da treba"
  },
  {
    "id": 107,
    "ch": 5,
    "de": "kochen",
    "ar": "يطبخ",
    "type": "verb",
    "example": "Ich koche heute Abend.",
    "en": "to cook",
    "tr": "yemek pişirmek",
    "ro": "a găti",
    "bs": "kuhati"
  },
  {
    "id": 108,
    "ch": 5,
    "de": "essen",
    "ar": "يأكل",
    "type": "verb",
    "example": "Was essen Sie gern?",
    "en": "to eat",
    "tr": "yemek yemek",
    "ro": "a mânca",
    "bs": "jesti"
  },
  {
    "id": 109,
    "ch": 5,
    "de": "lecker",
    "ar": "لذيذ",
    "type": "adj",
    "example": "Das Essen ist sehr lecker!",
    "en": "delicious",
    "tr": "lezzetli",
    "ro": "delicios",
    "bs": "ukusno"
  },
  {
    "id": 110,
    "ch": 5,
    "de": "das Rezept",
    "ar": "الوصفة",
    "type": "noun",
    "example": "Das Rezept ist einfach.",
    "en": "the recipe",
    "tr": "yemek tarifi",
    "ro": "reteta",
    "bs": "recept"
  },
  {
    "id": 111,
    "ch": 5,
    "de": "Guten Appetit!",
    "ar": "بالهناء والشفاء!",
    "type": "phrase",
    "example": "Das Essen ist fertig. Guten Appetit!",
    "en": "Enjoy your meal!",
    "tr": "Afiyet olsun!",
    "ro": "Poftă bună!",
    "bs": "Uživajte u obroku!"
  },
  {
    "id": 112,
    "ch": 6,
    "de": "die Familie",
    "ar": "العائلة",
    "type": "noun",
    "example": "Meine Familie ist groß.",
    "en": "the family",
    "tr": "aile",
    "ro": "familia",
    "bs": "porodica"
  },
  {
    "id": 113,
    "ch": 6,
    "de": "der Vater",
    "ar": "الأب",
    "type": "noun",
    "example": "Mein Vater heißt Peter.",
    "en": "the father",
    "tr": "baba",
    "ro": "tatăl",
    "bs": "otac"
  },
  {
    "id": 114,
    "ch": 6,
    "de": "die Mutter",
    "ar": "الأم",
    "type": "noun",
    "example": "Meine Mutter ist Ärztin.",
    "en": "the mother",
    "tr": "anne",
    "ro": "mama",
    "bs": "majka"
  },
  {
    "id": 115,
    "ch": 6,
    "de": "der Bruder",
    "ar": "الأخ",
    "type": "noun",
    "example": "Ich habe einen Bruder.",
    "en": "the brother",
    "tr": "erkek kardeş",
    "ro": "fratele",
    "bs": "brata"
  },
  {
    "id": 116,
    "ch": 6,
    "de": "die Schwester",
    "ar": "الأخت",
    "type": "noun",
    "example": "Meine Schwester ist 20 Jahre alt.",
    "en": "the sister",
    "tr": "kız kardeş",
    "ro": "sora",
    "bs": "sestra"
  },
  {
    "id": 117,
    "ch": 6,
    "de": "der Sohn",
    "ar": "الابن",
    "type": "noun",
    "example": "Mein Sohn heißt Tom.",
    "en": "the son",
    "tr": "oğul",
    "ro": "fiul",
    "bs": "sina"
  },
  {
    "id": 118,
    "ch": 6,
    "de": "die Tochter",
    "ar": "الابنة",
    "type": "noun",
    "example": "Ich habe eine Tochter.",
    "en": "the daughter",
    "tr": "kız evlat",
    "ro": "fiica",
    "bs": "kćer"
  },
  {
    "id": 119,
    "ch": 6,
    "de": "der Großvater",
    "ar": "الجد",
    "type": "noun",
    "example": "Mein Großvater ist 80 Jahre alt.",
    "en": "the grandfather",
    "tr": "büyükbaba / dede",
    "ro": "bunicul",
    "bs": "djed"
  },
  {
    "id": 120,
    "ch": 6,
    "de": "die Großmutter",
    "ar": "الجدة",
    "type": "noun",
    "example": "Die Großmutter kocht gut.",
    "en": "the grandmother",
    "tr": "büyükanne / nene",
    "ro": "bunica",
    "bs": "baka"
  },
  {
    "id": 121,
    "ch": 6,
    "de": "das Kind",
    "ar": "الطفل",
    "type": "noun",
    "example": "Ich habe zwei Kinder.",
    "en": "the child",
    "tr": "çocuk",
    "ro": "copilul",
    "bs": "dijete"
  },
  {
    "id": 122,
    "ch": 6,
    "de": "der Geburtstag",
    "ar": "عيد الميلاد",
    "type": "noun",
    "example": "Heute ist mein Geburtstag!",
    "en": "the birthday",
    "tr": "doğum günü",
    "ro": "ziua de naștere",
    "bs": "rođendan"
  },
  {
    "id": 123,
    "ch": 6,
    "de": "Herzlichen Glückwunsch!",
    "ar": "كل عام وأنت بخير! / مبروك!",
    "type": "phrase",
    "example": "Herzlichen Glückwunsch zum Geburtstag!",
    "en": "Congratulations!",
    "tr": "Tebrikler!",
    "ro": "Felicitări!",
    "bs": "Čestitamo!"
  },
  {
    "id": 124,
    "ch": 6,
    "de": "alt sein",
    "ar": "يبلغ من العمر",
    "type": "phrase",
    "example": "Ich bin 25 Jahre alt.",
    "en": "to be old / to be ... years old",
    "tr": "yaşında olmak / yaşlı olmak",
    "ro": "a fi în vârstă de / a avea ... ani",
    "bs": "biti star / biti ... godina star"
  },
  {
    "id": 125,
    "ch": 6,
    "de": "das Foto",
    "ar": "الصورة",
    "type": "noun",
    "example": "Das ist ein Familienfoto.",
    "en": "the photo",
    "tr": "fotoğraf",
    "ro": "fotografia",
    "bs": "fotografija"
  },
  {
    "id": 126,
    "ch": 7,
    "de": "die Wohnung",
    "ar": "الشقة",
    "type": "noun",
    "example": "Ich wohne in einer Wohnung.",
    "en": "the apartment / flat",
    "tr": "daire",
    "ro": "apartamentul",
    "bs": "stan/stan"
  },
  {
    "id": 127,
    "ch": 7,
    "de": "das Haus",
    "ar": "المنزل / البيت",
    "type": "noun",
    "example": "Das Haus ist groß.",
    "en": "the house",
    "tr": "ev",
    "ro": "casa",
    "bs": "kuću"
  },
  {
    "id": 128,
    "ch": 7,
    "de": "das Zimmer",
    "ar": "الغرفة",
    "type": "noun",
    "example": "Die Wohnung hat 3 Zimmer.",
    "en": "the room",
    "tr": "oda",
    "ro": "camera",
    "bs": "soba"
  },
  {
    "id": 129,
    "ch": 7,
    "de": "das Wohnzimmer",
    "ar": "غرفة المعيشة",
    "type": "noun",
    "example": "Im Wohnzimmer gibt es ein Sofa.",
    "en": "the living room",
    "tr": "oturma odası",
    "ro": "camera de zi / sufrageria",
    "bs": "dnevni boravak"
  },
  {
    "id": 130,
    "ch": 7,
    "de": "das Schlafzimmer",
    "ar": "غرفة النوم",
    "type": "noun",
    "example": "Das Schlafzimmer ist ruhig.",
    "en": "the bedroom",
    "tr": "yatak odası",
    "ro": "dormitorul",
    "bs": "spavaća soba"
  },
  {
    "id": 131,
    "ch": 7,
    "de": "die Küche",
    "ar": "المطبخ",
    "type": "noun",
    "example": "Ich koche in der Küche.",
    "en": "the kitchen",
    "tr": "mutfak",
    "ro": "bucataria",
    "bs": "kuhinja"
  },
  {
    "id": 132,
    "ch": 7,
    "de": "das Bad/Badezimmer",
    "ar": "الحمام",
    "type": "noun",
    "example": "Das Bad hat eine Dusche.",
    "en": "the bathroom",
    "tr": "banyo",
    "ro": "baia",
    "bs": "kupatilo"
  },
  {
    "id": 133,
    "ch": 7,
    "de": "die Miete",
    "ar": "الإيجار",
    "type": "noun",
    "example": "Die Miete kostet 800 Euro.",
    "en": "the rent",
    "tr": "kira",
    "ro": "chiria",
    "bs": "najam"
  },
  {
    "id": 134,
    "ch": 7,
    "de": "der Stock / die Etage",
    "ar": "الطابق",
    "type": "noun",
    "example": "Im 3. Stock.",
    "en": "the floor / story",
    "tr": "kat",
    "ro": "etajul",
    "bs": "sprat / priča"
  },
  {
    "id": 135,
    "ch": 7,
    "de": "das Sofa",
    "ar": "الأريكة",
    "type": "noun",
    "example": "Das Sofa ist bequem.",
    "en": "the sofa",
    "tr": "kanepe / koltuk",
    "ro": "canapeaua",
    "bs": "sofa"
  },
  {
    "id": 136,
    "ch": 7,
    "de": "der Schrank",
    "ar": "الخزانة",
    "type": "noun",
    "example": "Der Schrank ist groß.",
    "en": "the cupboard / wardrobe",
    "tr": "dolap",
    "ro": "dulapul",
    "bs": "ormar/ormar"
  },
  {
    "id": 137,
    "ch": 7,
    "de": "das Bett",
    "ar": "السرير",
    "type": "noun",
    "example": "Das Bett ist neu.",
    "en": "the bed",
    "tr": "yatak",
    "ro": "patul",
    "bs": "krevet"
  },
  {
    "id": 138,
    "ch": 7,
    "de": "der Tisch",
    "ar": "الطاولة",
    "type": "noun",
    "example": "Der Tisch ist aus Holz.",
    "en": "the table",
    "tr": "masa",
    "ro": "masa",
    "bs": "sto"
  },
  {
    "id": 139,
    "ch": 7,
    "de": "der Stuhl",
    "ar": "الكرسي",
    "type": "noun",
    "example": "Nehmen Sie Platz!",
    "en": "the chair",
    "tr": "sandalye",
    "ro": "scaunul",
    "bs": "stolica"
  },
  {
    "id": 140,
    "ch": 7,
    "de": "auf",
    "ar": "على",
    "type": "prep",
    "example": "Das Buch ist auf dem Tisch.",
    "en": "on / upon",
    "tr": "üzerinde",
    "ro": "pe",
    "bs": "na / na"
  },
  {
    "id": 141,
    "ch": 7,
    "de": "neben",
    "ar": "بجانب",
    "type": "prep",
    "example": "Die Lampe ist neben dem Sofa.",
    "en": "next to / beside",
    "tr": "yanında",
    "ro": "lângă",
    "bs": "pored / pored"
  },
  {
    "id": 142,
    "ch": 7,
    "de": "vor",
    "ar": "أمام",
    "type": "prep",
    "example": "Der Schrank steht vor dem Fenster.",
    "en": "in front of / before",
    "tr": "önünde",
    "ro": "în fața",
    "bs": "ispred / prije"
  },
  {
    "id": 143,
    "ch": 7,
    "de": "hinter",
    "ar": "خلف",
    "type": "prep",
    "example": "Das Bild ist hinter dem Sofa.",
    "en": "behind",
    "tr": "arkasında",
    "ro": "în spatele",
    "bs": "iza"
  },
  {
    "id": 144,
    "ch": 8,
    "de": "der Kopf",
    "ar": "الرأس",
    "type": "noun",
    "example": "Mein Kopf tut weh.",
    "en": "the head",
    "tr": "baş / kafa",
    "ro": "capul",
    "bs": "glava"
  },
  {
    "id": 145,
    "ch": 8,
    "de": "der Bauch",
    "ar": "البطن",
    "type": "noun",
    "example": "Ich habe Bauchschmerzen.",
    "en": "the stomach / belly",
    "tr": "karın",
    "ro": "stomacul",
    "bs": "stomak/trbuh"
  },
  {
    "id": 146,
    "ch": 8,
    "de": "der Hals",
    "ar": "الحلق / الرقبة",
    "type": "noun",
    "example": "Mein Hals tut weh.",
    "en": "the neck / throat",
    "tr": "boyun / boğaz",
    "ro": "gâtul",
    "bs": "vrat / grlo"
  },
  {
    "id": 147,
    "ch": 8,
    "de": "der Rücken",
    "ar": "الظهر",
    "type": "noun",
    "example": "Rückenschmerzen.",
    "en": "the back",
    "tr": "sırt",
    "ro": "spatele",
    "bs": "leđa"
  },
  {
    "id": 148,
    "ch": 8,
    "de": "Kopfschmerzen",
    "ar": "صداع الرأس",
    "type": "noun",
    "example": "Ich habe Kopfschmerzen.",
    "en": "headache",
    "tr": "baş ağrısı",
    "ro": "durere de cap",
    "bs": "glavobolja"
  },
  {
    "id": 149,
    "ch": 8,
    "de": "das Fieber",
    "ar": "الحمى / السخونة",
    "type": "noun",
    "example": "Ich habe Fieber.",
    "en": "the fever",
    "tr": "ateş (vücut)",
    "ro": "febra",
    "bs": "groznica"
  },
  {
    "id": 150,
    "ch": 8,
    "de": "die Erkältung",
    "ar": "البرد / الرشح",
    "type": "noun",
    "example": "Ich habe eine Erkältung.",
    "en": "the cold / common cold",
    "tr": "soğuk algınlığı",
    "ro": "răceala",
    "bs": "prehlada / prehlada"
  },
  {
    "id": 151,
    "ch": 8,
    "de": "der Arzt / die Ärztin",
    "ar": "الطبيب / الطبيبة",
    "type": "noun",
    "example": "Ich gehe zum Arzt.",
    "en": "the doctor",
    "tr": "doktor",
    "ro": "medicul / doctorul",
    "bs": "doktora"
  },
  {
    "id": 152,
    "ch": 8,
    "de": "das Krankenhaus",
    "ar": "المستشفى",
    "type": "noun",
    "example": "Sie arbeitet im Krankenhaus.",
    "en": "the hospital",
    "tr": "hastane",
    "ro": "spitalul",
    "bs": "bolnicu"
  },
  {
    "id": 153,
    "ch": 8,
    "de": "das Medikament",
    "ar": "الدواء",
    "type": "noun",
    "example": "Nehmen Sie Medikamente.",
    "en": "the medicine",
    "tr": "ilaç",
    "ro": "medicamentul",
    "bs": "lijek"
  },
  {
    "id": 154,
    "ch": 8,
    "de": "müssen",
    "ar": "يجب",
    "type": "verb",
    "example": "Ich muss zum Arzt gehen.",
    "en": "must / to have to",
    "tr": "zorunda olmak",
    "ro": "a trebui (obligație)",
    "bs": "mora / da se mora"
  },
  {
    "id": 155,
    "ch": 8,
    "de": "können",
    "ar": "يستطيع / يمكن",
    "type": "verb",
    "example": "Ich kann nicht kommen.",
    "en": "can / to be able to",
    "tr": "yapabilmek",
    "ro": "a putea (abilitate)",
    "bs": "mogu / da mogu"
  },
  {
    "id": 156,
    "ch": 8,
    "de": "dürfen",
    "ar": "يجوز / مسموح",
    "type": "verb",
    "example": "Man darf nicht rauchen.",
    "en": "may / to be allowed to",
    "tr": "izinli olmak",
    "ro": "a avea voie (permisiune)",
    "bs": "može / biti dozvoljeno"
  },
  {
    "id": 157,
    "ch": 8,
    "de": "wehtun",
    "ar": "يؤلم",
    "type": "verb",
    "example": "Mein Kopf tut weh.",
    "en": "to hurt / ache",
    "tr": "ağrımak / acımak",
    "ro": "a răni",
    "bs": "povrediti / boljeti"
  },
  {
    "id": 158,
    "ch": 8,
    "de": "gesund",
    "ar": "بصحة جيدة / صحي",
    "type": "adj",
    "example": "Sport ist gesund.",
    "en": "healthy / well",
    "tr": "sağlıklı / sıhhatli",
    "ro": "sănătos",
    "bs": "zdravo/dobro"
  },
  {
    "id": 159,
    "ch": 8,
    "de": "der Sport",
    "ar": "الرياضة",
    "type": "noun",
    "example": "Ich mache gern Sport.",
    "en": "the sport",
    "tr": "spor",
    "ro": "sportul",
    "bs": "sport"
  },
  {
    "id": 160,
    "ch": 9,
    "de": "der Zug",
    "ar": "القطار",
    "type": "noun",
    "example": "Der Zug fährt um 10 Uhr ab.",
    "en": "the train",
    "tr": "tren",
    "ro": "trenul",
    "bs": "voz"
  },
  {
    "id": 161,
    "ch": 9,
    "de": "das Auto",
    "ar": "السيارة",
    "type": "noun",
    "example": "Ich fahre mit dem Auto.",
    "en": "the car",
    "tr": "araba",
    "ro": "mașina",
    "bs": "auto"
  },
  {
    "id": 162,
    "ch": 9,
    "de": "das Fahrrad",
    "ar": "الدراجة",
    "type": "noun",
    "example": "Ich fahre gern Fahrrad.",
    "en": "the bicycle",
    "tr": "bisiklet",
    "ro": "bicicleta",
    "bs": "bicikl"
  },
  {
    "id": 163,
    "ch": 9,
    "de": "die U-Bahn",
    "ar": "مترو الأنفاق",
    "type": "noun",
    "example": "Nehmen Sie die U-Bahn.",
    "en": "the subway / metro",
    "tr": "metro",
    "ro": "metroul",
    "bs": "metro / metro"
  },
  {
    "id": 164,
    "ch": 9,
    "de": "der Bus",
    "ar": "الحافلة",
    "type": "noun",
    "example": "Der Bus fährt alle 10 Minuten.",
    "en": "the bus",
    "tr": "otobüs",
    "ro": "autobuzul",
    "bs": "autobus"
  },
  {
    "id": 165,
    "ch": 9,
    "de": "die Fahrkarte",
    "ar": "التذكرة",
    "type": "noun",
    "example": "Eine Fahrkarte nach Berlin.",
    "en": "the ticket",
    "tr": "bilet",
    "ro": "biletul",
    "bs": "kartu"
  },
  {
    "id": 166,
    "ch": 9,
    "de": "der Bahnhof",
    "ar": "محطة القطار",
    "type": "noun",
    "example": "Der Bahnhof ist groß.",
    "en": "the train station",
    "tr": "tren istasyonu",
    "ro": "gara",
    "bs": "željeznička stanica"
  },
  {
    "id": 167,
    "ch": 9,
    "de": "das Gleis",
    "ar": "الرصيف / السكة",
    "type": "noun",
    "example": "Gleis 7.",
    "en": "the platform / track",
    "tr": "peron / ray",
    "ro": "peronul / linia",
    "bs": "platforma / staza"
  },
  {
    "id": 168,
    "ch": 9,
    "de": "abfahren",
    "ar": "يغادر / يقلع",
    "type": "verb",
    "example": "Der Zug fährt um 10 ab.",
    "en": "to depart / leave",
    "tr": "hareket etmek",
    "ro": "a pleca / a demara",
    "bs": "otići / otići"
  },
  {
    "id": 169,
    "ch": 9,
    "de": "ankommen",
    "ar": "يصل",
    "type": "verb",
    "example": "Der Zug kommt um 14 Uhr an.",
    "en": "to arrive",
    "tr": "varmak",
    "ro": "a sosi",
    "bs": "stići"
  },
  {
    "id": 170,
    "ch": 9,
    "de": "geradeaus",
    "ar": "إلى الأمام مباشرة",
    "type": "adv",
    "example": "Gehen Sie geradeaus.",
    "en": "straight ahead",
    "tr": "düz / dosdoğru",
    "ro": "drept înainte",
    "bs": "pravo naprijed"
  },
  {
    "id": 171,
    "ch": 9,
    "de": "rechts",
    "ar": "يميناً",
    "type": "adv",
    "example": "Biegen Sie rechts ab.",
    "en": "right",
    "tr": "sağ",
    "ro": "corect",
    "bs": "u pravu"
  },
  {
    "id": 172,
    "ch": 9,
    "de": "links",
    "ar": "يساراً",
    "type": "adv",
    "example": "Die nächste Straße links.",
    "en": "left",
    "tr": "sol",
    "ro": "stânga",
    "bs": "lijevo"
  },
  {
    "id": 173,
    "ch": 9,
    "de": "hin und zurück",
    "ar": "ذهاباً وعودة",
    "type": "phrase",
    "example": "Eine Fahrkarte hin und zurück.",
    "en": "round trip",
    "tr": "gidiş-dönüş",
    "ro": "dus-întors",
    "bs": "povratno putovanje"
  },
  {
    "id": 174,
    "ch": 10,
    "de": "das Hobby",
    "ar": "الهواية",
    "type": "noun",
    "example": "Was ist dein Hobby?",
    "en": "the hobby",
    "tr": "hobi",
    "ro": "hobby-ul",
    "bs": "hobi"
  },
  {
    "id": 175,
    "ch": 10,
    "de": "der Fußball",
    "ar": "كرة القدم",
    "type": "noun",
    "example": "Ich spiele gern Fußball.",
    "en": "the football / soccer",
    "tr": "futbol",
    "ro": "fotbalul",
    "bs": "fudbal / fudbal"
  },
  {
    "id": 176,
    "ch": 10,
    "de": "das Tennis",
    "ar": "التنس",
    "type": "noun",
    "example": "Spielst du Tennis?",
    "en": "the tennis",
    "tr": "tenis",
    "ro": "tenisul",
    "bs": "tenis"
  },
  {
    "id": 177,
    "ch": 10,
    "de": "das Schwimmen",
    "ar": "السباحة",
    "type": "noun",
    "example": "Schwimmen ist gesund.",
    "en": "the swimming",
    "tr": "yüzme",
    "ro": "înotul",
    "bs": "plivanje"
  },
  {
    "id": 178,
    "ch": 10,
    "de": "die Musik",
    "ar": "الموسيقى",
    "type": "noun",
    "example": "Ich höre gern Musik.",
    "en": "the music",
    "tr": "müzik",
    "ro": "muzica",
    "bs": "muzika"
  },
  {
    "id": 179,
    "ch": 10,
    "de": "lesen",
    "ar": "يقرأ",
    "type": "verb",
    "example": "Ich lese gern Bücher.",
    "en": "to read",
    "tr": "okumak",
    "ro": "a citi",
    "bs": "čitati"
  },
  {
    "id": 180,
    "ch": 10,
    "de": "spielen",
    "ar": "يلعب",
    "type": "verb",
    "example": "Ich spiele Gitarre.",
    "en": "to play",
    "tr": "oynamak / çalmak (müzik)",
    "ro": "a juca",
    "bs": "igrati"
  },
  {
    "id": 181,
    "ch": 10,
    "de": "hören",
    "ar": "يسمع / يستمع",
    "type": "verb",
    "example": "Ich höre Musik.",
    "en": "to hear / listen",
    "tr": "duymak / dinlemek",
    "ro": "a auzi",
    "bs": "čuti/slušati"
  },
  {
    "id": 182,
    "ch": 10,
    "de": "gern",
    "ar": "يحب / بسرور",
    "type": "adv",
    "example": "Ich spiele gern Fußball.",
    "en": "gladly / with pleasure",
    "tr": "severek / memnuniyetle",
    "ro": "bucuros",
    "bs": "rado / sa zadovoljstvom"
  },
  {
    "id": 183,
    "ch": 10,
    "de": "nicht gern",
    "ar": "لا يحب",
    "type": "phrase",
    "example": "Ich lese nicht gern.",
    "en": "not gladly / dislike",
    "tr": "sevmeden / hoşlanmayarak",
    "ro": "nu cu bucurie",
    "bs": "ne rado/ne sviđa mi se"
  },
  {
    "id": 184,
    "ch": 10,
    "de": "der Spaß",
    "ar": "المتعة / المرح",
    "type": "noun",
    "example": "Das macht Spaß!",
    "en": "the fun",
    "tr": "eğlence / keyif",
    "ro": "distracția",
    "bs": "zabava"
  },
  {
    "id": 185,
    "ch": 10,
    "de": "das Kino",
    "ar": "السينما",
    "type": "noun",
    "example": "Gehen wir ins Kino?",
    "en": "the cinema / movie theater",
    "tr": "sinema",
    "ro": "cinematograful",
    "bs": "kino/bioskop"
  },
  {
    "id": 186,
    "ch": 10,
    "de": "das Konzert",
    "ar": "الحفلة الموسيقية",
    "type": "noun",
    "example": "Morgen ist ein Konzert.",
    "en": "the concert",
    "tr": "konser",
    "ro": "concertul",
    "bs": "koncert"
  },
  {
    "id": 187,
    "ch": 10,
    "de": "die Einladung",
    "ar": "الدعوة",
    "type": "noun",
    "example": "Ich habe eine Einladung.",
    "en": "the invitation",
    "tr": "davet",
    "ro": "invitația",
    "bs": "pozivnicu"
  },
  {
    "id": 188,
    "ch": 11,
    "de": "die Arbeit / der Job",
    "ar": "العمل / الوظيفة",
    "type": "noun",
    "example": "Ich suche Arbeit.",
    "en": "the work / job",
    "tr": "iş / meslek",
    "ro": "lucrarea",
    "bs": "posao/posao"
  },
  {
    "id": 189,
    "ch": 11,
    "de": "der Beruf",
    "ar": "المهنة / الحرفة",
    "type": "noun",
    "example": "Was sind Sie von Beruf?",
    "en": "the profession / occupation",
    "tr": "meslek",
    "ro": "profesia",
    "bs": "profesija / zanimanje"
  },
  {
    "id": 190,
    "ch": 11,
    "de": "der Arzt",
    "ar": "الطبيب",
    "type": "noun",
    "example": "Ich bin Arzt.",
    "en": "the doctor (male)",
    "tr": "erkek doktor",
    "ro": "doctorul (masculin)",
    "bs": "doktor (muško)"
  },
  {
    "id": 191,
    "ch": 11,
    "de": "der Lehrer",
    "ar": "المعلم",
    "type": "noun",
    "example": "Er ist Lehrer.",
    "en": "the teacher",
    "tr": "öğretmen",
    "ro": "profesorul",
    "bs": "nastavnik"
  },
  {
    "id": 192,
    "ch": 11,
    "de": "der Ingenieur",
    "ar": "المهندس",
    "type": "noun",
    "example": "Ich bin Ingenieur.",
    "en": "the engineer",
    "tr": "mühendis",
    "ro": "inginerul",
    "bs": "inženjer"
  },
  {
    "id": 193,
    "ch": 11,
    "de": "der Koch",
    "ar": "الطباخ",
    "type": "noun",
    "example": "Der Koch kocht gut.",
    "en": "the cook / chef",
    "tr": "aşçı",
    "ro": "bucătarul",
    "bs": "kuhar / kuhar"
  },
  {
    "id": 194,
    "ch": 11,
    "de": "der Verkäufer",
    "ar": "البائع",
    "type": "noun",
    "example": "Der Verkäufer ist freundlich.",
    "en": "the salesman / seller",
    "tr": "satıcı / tezgahtar",
    "ro": "vânzătorul",
    "bs": "prodavač/prodavac"
  },
  {
    "id": 195,
    "ch": 11,
    "de": "das Büro",
    "ar": "المكتب",
    "type": "noun",
    "example": "Ich arbeite im Büro.",
    "en": "the office",
    "tr": "ofis / büro",
    "ro": "biroul",
    "bs": "kancelariju"
  },
  {
    "id": 196,
    "ch": 11,
    "de": "arbeiten",
    "ar": "يعمل",
    "type": "verb",
    "example": "Ich arbeite 40 Stunden.",
    "en": "to work",
    "tr": "çalışmak",
    "ro": "a lucra",
    "bs": "na posao"
  },
  {
    "id": 197,
    "ch": 11,
    "de": "das Gehalt",
    "ar": "الراتب",
    "type": "noun",
    "example": "Das Gehalt ist 2500 Euro.",
    "en": "the salary",
    "tr": "maaş",
    "ro": "salariul",
    "bs": "platu"
  },
  {
    "id": 198,
    "ch": 11,
    "de": "die Stunde",
    "ar": "الساعة (وحدة زمن)",
    "type": "noun",
    "example": "40 Stunden pro Woche.",
    "en": "the hour",
    "tr": "saat (zaman birimi)",
    "ro": "ora",
    "bs": "sat"
  },
  {
    "id": 199,
    "ch": 12,
    "de": "das Restaurant",
    "ar": "المطعم",
    "type": "noun",
    "example": "Wir gehen ins Restaurant.",
    "en": "the restaurant",
    "tr": "restoran",
    "ro": "restaurantul",
    "bs": "restoran"
  },
  {
    "id": 200,
    "ch": 12,
    "de": "die Speisekarte",
    "ar": "قائمة الطعام",
    "type": "noun",
    "example": "Die Speisekarte, bitte!",
    "en": "the menu",
    "tr": "yemek menüsü",
    "ro": "meniul",
    "bs": "meni"
  },
  {
    "id": 201,
    "ch": 12,
    "de": "der Kellner",
    "ar": "النادل",
    "type": "noun",
    "example": "Der Kellner ist freundlich.",
    "en": "the waiter",
    "tr": "garson",
    "ro": "chelnerul",
    "bs": "konobar"
  },
  {
    "id": 202,
    "ch": 12,
    "de": "die Vorspeise",
    "ar": "المقبلات",
    "type": "noun",
    "example": "Als Vorspeise möchte ich Suppe.",
    "en": "the appetizer / starter",
    "tr": "başlangıç / meze",
    "ro": "aperitivul",
    "bs": "predjelo / predjelo"
  },
  {
    "id": 203,
    "ch": 12,
    "de": "die Hauptspeise",
    "ar": "الطبق الرئيسي",
    "type": "noun",
    "example": "Als Hauptspeise das Schnitzel.",
    "en": "the main course",
    "tr": "ana yemek",
    "ro": "felul principal",
    "bs": "glavno jelo"
  },
  {
    "id": 204,
    "ch": 12,
    "de": "das Dessert",
    "ar": "الحلوى",
    "type": "noun",
    "example": "Als Dessert ein Eis.",
    "en": "the dessert",
    "tr": "tatlı",
    "ro": "desertul",
    "bs": "desert"
  },
  {
    "id": 205,
    "ch": 12,
    "de": "das Schnitzel",
    "ar": "الشنيتزل (قطعة لحم مقلية)",
    "type": "noun",
    "example": "Das Schnitzel ist lecker.",
    "en": "the schnitzel",
    "tr": "şinitzel",
    "ro": "șnițelul",
    "bs": "šnicle"
  },
  {
    "id": 206,
    "ch": 12,
    "de": "die Suppe",
    "ar": "الشوربة",
    "type": "noun",
    "example": "Eine Tomatensuppe, bitte.",
    "en": "the soup",
    "tr": "çorba",
    "ro": "supa",
    "bs": "supu"
  },
  {
    "id": 207,
    "ch": 12,
    "de": "bestellen",
    "ar": "يطلب (في المطعم)",
    "type": "verb",
    "example": "Was möchten Sie bestellen?",
    "en": "to order",
    "tr": "sipariş vermek",
    "ro": "a comanda",
    "bs": "naručiti"
  },
  {
    "id": 208,
    "ch": 12,
    "de": "Zahlen, bitte!",
    "ar": "الحساب من فضلك!",
    "type": "phrase",
    "example": "Entschuldigung! Zahlen, bitte!",
    "en": "The bill, please!",
    "tr": "Hesap lütfen!",
    "ro": "Factura, vă rog!",
    "bs": "Račun, molim!"
  },
  {
    "id": 209,
    "ch": 12,
    "de": "Stimmt so.",
    "ar": "احتفظ بالباقي. (عند الدفع)",
    "type": "phrase",
    "example": "Stimmt so. Das ist für Sie.",
    "en": "Keep the change.",
    "tr": "Üstü kalsın.",
    "ro": "Păstrați restul.",
    "bs": "Zadrži kusur."
  },
  {
    "id": 210,
    "ch": 12,
    "de": "das Trinkgeld",
    "ar": "البقشيش / الإكرامية",
    "type": "noun",
    "example": "Ich gebe Trinkgeld.",
    "en": "the tip",
    "tr": "bahşiş",
    "ro": "vârful",
    "bs": "vrh"
  },
  {
    "id": 211,
    "ch": 1,
    "de": "ja",
    "ar": "نعم",
    "type": "phrase",
    "example": "Ja, ich komme aus Berlin.",
    "en": "yes",
    "tr": "evet",
    "ro": "Da",
    "bs": "da"
  },
  {
    "id": 212,
    "ch": 1,
    "de": "nein",
    "ar": "لا",
    "type": "phrase",
    "example": "Nein, ich wohne nicht in Berlin.",
    "en": "no",
    "tr": "hayır",
    "ro": "nu",
    "bs": "br"
  },
  {
    "id": 213,
    "ch": 1,
    "de": "und",
    "ar": "و",
    "type": "phrase",
    "example": "Ich bin müde und krank.",
    "en": "and",
    "tr": "ve",
    "ro": "şi",
    "bs": "i"
  },
  {
    "id": 214,
    "ch": 1,
    "de": "oder",
    "ar": "أو",
    "type": "phrase",
    "example": "Kaffee oder Tee?",
    "en": "or",
    "tr": "veya",
    "ro": "sau",
    "bs": "ili"
  },
  {
    "id": 215,
    "ch": 1,
    "de": "aber",
    "ar": "لكن",
    "type": "phrase",
    "example": "Das ist teuer, aber schön.",
    "en": "but",
    "tr": "ama / fakat",
    "ro": "dar",
    "bs": "ali"
  },
  {
    "id": 216,
    "ch": 2,
    "de": "sehr",
    "ar": "جداً",
    "type": "adv",
    "example": "Das ist sehr lecker!",
    "en": "very",
    "tr": "çok",
    "ro": "foarte",
    "bs": "vrlo"
  },
  {
    "id": 217,
    "ch": 1,
    "de": "auch",
    "ar": "أيضاً",
    "type": "adv",
    "example": "Ich spreche auch Englisch.",
    "en": "also / too",
    "tr": "de / da / hem de",
    "ro": "asemenea",
    "bs": "također / također"
  },
  {
    "id": 218,
    "ch": 1,
    "de": "nicht",
    "ar": "لا / ليس",
    "type": "adv",
    "example": "Das ist nicht gut.",
    "en": "not",
    "tr": "değil / -me (olumsuzluk)",
    "ro": "nu",
    "bs": "ne"
  },
  {
    "id": 219,
    "ch": 1,
    "de": "viel",
    "ar": "كثير",
    "type": "adv",
    "example": "Ich lerne viel.",
    "en": "much / many",
    "tr": "çok / fazla",
    "ro": "mult",
    "bs": "mnogo / mnogo"
  },
  {
    "id": 220,
    "ch": 2,
    "de": "heute",
    "ar": "اليوم",
    "type": "adv",
    "example": "Heute ist Montag.",
    "en": "today",
    "tr": "bugün",
    "ro": "astăzi",
    "bs": "danas"
  },
  {
    "id": 221,
    "ch": 2,
    "de": "morgen",
    "ar": "غداً",
    "type": "adv",
    "example": "Morgen habe ich Kurs.",
    "en": "tomorrow",
    "tr": "yarın",
    "ro": "mâine",
    "bs": "sutra"
  },
  {
    "id": 222,
    "ch": 4,
    "de": "jetzt",
    "ar": "الآن",
    "type": "adv",
    "example": "Was machen Sie jetzt?",
    "en": "now",
    "tr": "şimdi",
    "ro": "acum",
    "bs": "sada"
  },
  {
    "id": 223,
    "ch": 4,
    "de": "dann",
    "ar": "ثم / بعدها",
    "type": "adv",
    "example": "Ich frühstücke, dann gehe ich.",
    "en": "then",
    "tr": "sonra / o zaman",
    "ro": "apoi",
    "bs": "onda"
  },
  {
    "id": 224,
    "ch": 1,
    "de": "Entschuldigung!",
    "ar": "عذراً! / معذرة!",
    "type": "phrase",
    "example": "Entschuldigung! Wie spät ist es?",
    "en": "Excuse me / Sorry!",
    "tr": "Affedersiniz / Özür dilerim!",
    "ro": "Scuzați-mă",
    "bs": "Izvinite / Izvinite!"
  },
  {
    "id": 225,
    "ch": 1,
    "de": "noch einmal",
    "ar": "مرة أخرى",
    "type": "phrase",
    "example": "Sagen Sie das noch einmal, bitte.",
    "en": "once again",
    "tr": "bir kez daha",
    "ro": "încă o dată",
    "bs": "još jednom"
  }
];

// Type labels for display
const TYPE_LABELS = {
  "noun": {
    "ar": "اسم",
    "en": "Noun",
    "tr": "İsim",
    "de": "Nomen",
    "ro": "Substantiv",
    "bs": "Imenica",
    "color": "#4f8ef7"
  },
  "verb": {
    "ar": "فعل",
    "en": "Verb",
    "tr": "Fiil",
    "de": "Verb",
    "ro": "Verb",
    "bs": "Glagol",
    "color": "#f59e0b"
  },
  "adj": {
    "ar": "صفة",
    "en": "Adjective",
    "tr": "Sıfat",
    "de": "Adjektiv",
    "ro": "Adjectiv",
    "bs": "Pridjev",
    "color": "#34d399"
  },
  "phrase": {
    "ar": "عبارة",
    "en": "Phrase",
    "tr": "Kalıp",
    "de": "Ausdruck",
    "ro": "Expresie",
    "bs": "Izraz",
    "color": "#a78bfa"
  },
  "pronoun": {
    "ar": "ضمير",
    "en": "Pronoun",
    "tr": "Zamir",
    "de": "Pronomen",
    "ro": "Pronume",
    "bs": "Zamjenica",
    "color": "#60a5fa"
  },
  "number": {
    "ar": "رقم",
    "en": "Number",
    "tr": "Sayı",
    "de": "Zahl",
    "ro": "Număr",
    "bs": "Broj",
    "color": "#fbbf24"
  },
  "grammar": {
    "ar": "قاعدة",
    "en": "Grammar",
    "tr": "Dilbilgisi",
    "de": "Grammatik",
    "ro": "Gramatică",
    "bs": "Gramatika",
    "color": "#f87171"
  },
  "adv": {
    "ar": "ظرف",
    "en": "Adverb",
    "tr": "Zarf",
    "de": "Adverb",
    "ro": "Adverb",
    "bs": "Prilog",
    "color": "#34d399"
  },
  "prep": {
    "ar": "حرف جر",
    "en": "Preposition",
    "tr": "Edat",
    "de": "Präposition",
    "ro": "Prepoziție",
    "bs": "Prijedlog",
    "color": "#fb923c"
  },
  "time": {
    "ar": "وقت",
    "en": "Time",
    "tr": "Zaman",
    "de": "Zeit",
    "ro": "Timp",
    "bs": "Vrijeme",
    "color": "#a78bfa"
  }
};
